export const CREATE_EPISODE_CONTENT = 'CREATE_EPISODE_CONTENT';
export const EDIT_EPISODE_CONTENT = 'EDIT_EPISODE_CONTENT';
export const CLEAR_EPISODE_CONTENT = 'CLEAR_EPISODE_CONTENT';

export const SELECT_EPISODE_CONTENT = 'SELECT_EPISODE_CONTENT';
export const INSERT_EPISODE_CONTENT = 'INSERT_EPISODE_CONTENT';
export const UPDATE_EPISODE_CONTENT = 'UPDATE_EPISODE_CONTENT';
export const REMOVE_EPISODE_CONTENT = 'REMOVE_EPISODE_CONTENT';
export const MOVE_EPISODE_CONTENT_UP = 'MOVE_EPISODE_CONTENT_UP';
export const MOVE_EPISODE_CONTENT_DOWN = 'MOVE_EPISODE_CONTENT_DOWN';

export const EPISODE_CONTENT_APPLY_DATA_FROM_WORKSHOP = 'EPISODE_CONTENT_APPLY_DATA_FROM_WORKSHOP';