export const PROCESS_FIELDS = [
    "AudioIniURL",
    "AudioIniComment",
    "InstrToAudioEdt",
    "AudioProcURL",
    "TranscriptURL",
    "PicDescriptionURL",
    "PicSrcURL",
    "PicAuthorURL",
    "PicFinalURL",
    "TechTransTiterURL",
    "TechTransEditURL",
    "RefsURL",
    "AudioFinalURL",
    "AudioNotes",
    "TechTransTimeURL",
    "TechTransMusicURL",
    "AllCompsFinalURL"
]
