export const GET_COURSE_AUTHORS_REQUEST = 'GET_COURSE_AUTHORS_REQUEST';
export const GET_COURSE_AUTHORS_SUCCESS = 'GET_COURSE_AUTHORS_SUCCESS';
export const GET_COURSE_AUTHORS_FAIL = 'GET_COURSE_AUTHORS_FAIL';