import { SearchResult } from '#types/images';

const searchResult: SearchResult = {
  hits: [
    {
      Id: 8491,
      IdArtifact: null,
      Name: null,
      PubDate: '2019-01-25T12:17:52.000Z',
      _score: 40852.363,
      IsFragment: false,
      Status: 1,
      URL: 'https://dev.magisteria.ru/data/2018/01/Stater-kilikijskogo-satrapa-Balakra.-333-324-gg.-do-n.e.-Serebro.-Avers-Baal-Tars-na-trone.-Revers-golova-Afiny.jpg',
      MetaInfo: {
        path: '2018/01/',
        'mime-type': 'image/jpeg',
        size: {
          width: 765,
          height: 768,
        },
        content: {
          s: 'https://dev.magisteria.ru/data/2018/01/Stater-kilikijskogo-satrapa-Balakra.-333-324-gg.-do-n.e.-Serebro.-Avers-Baal-Tars-na-trone.-Revers-golova-Afiny-360x361.jpg',
        },
        icon: 'https://dev.magisteria.ru/data/2018/01/Stater-kilikijskogo-satrapa-Balakra.-333-324-gg.-do-n.e.-Serebro.-Avers-Baal-Tars-na-trone.-Revers-golova-Afiny-150x150.jpg',
      },
      Authors: [],
      Museums: [],
      PicName: 'Статер киликийского сатрапа Балакра. 333–324 гг. до н.э.',
      PicDescription: 'Серебро. Аверс – Баал-Тарс на троне. Реверс – голова Афины',
      ArtifactText: null,
      AuthorText: null,
      MuseumText: null,
      highlight: {
        PicDescription: [
          'Аверс – Баал-Тарс на <em>троне</em>. Реверс – голова Афины',
        ],
      },
      type: 'picture',
    },
    {
      Id: 4806,
      IdArtifact: null,
      Name: null,
      PubDate: '2019-01-25T12:17:44.000Z',
      _score: 40335.33,
      IsFragment: false,
      Status: 1,
      URL: 'https://dev.magisteria.ru/data/2016/10/Tron-Lyudovizi-2.jpg',
      MetaInfo: {
        path: '2016/10/',
        'mime-type': 'image/jpeg',
        size: {
          width: 1424,
          height: 1070,
        },
        content: {
          l: 'https://dev.magisteria.ru/data/2016/10/Tron-Lyudovizi-2-1366x1026.jpg',
          m: 'https://dev.magisteria.ru/data/2016/10/Tron-Lyudovizi-2-768x577.jpg',
          s: 'https://dev.magisteria.ru/data/2016/10/Tron-Lyudovizi-2-360x271.jpg',
        },
        icon: 'https://dev.magisteria.ru/data/2016/10/Tron-Lyudovizi-2-150x150.jpg',
      },
      Authors: [],
      Museums: [],
      PicName: '«Трон Людовизи»',
      PicDescription: null,
      ArtifactText: null,
      AuthorText: null,
      MuseumText: null,
      highlight: {
        PicName: [
          '«<em>Трон</em> Людовизи»',
        ],
      },
      type: 'picture',
    },
    {
      Id: 4807,
      IdArtifact: null,
      Name: null,
      PubDate: '2019-01-25T12:17:44.000Z',
      _score: 40335.33,
      IsFragment: false,
      Status: 1,
      URL: 'https://dev.magisteria.ru/data/2016/10/Tron-Lyudovizi-3.jpg',
      MetaInfo: {
        path: '2016/10/',
        'mime-type': 'image/jpeg',
        size: {
          width: 1280,
          height: 806,
        },
        content: {
          m: 'https://dev.magisteria.ru/data/2016/10/Tron-Lyudovizi-3-768x484.jpg',
          s: 'https://dev.magisteria.ru/data/2016/10/Tron-Lyudovizi-3-360x227.jpg',
        },
        icon: 'https://dev.magisteria.ru/data/2016/10/Tron-Lyudovizi-3-150x150.jpg',
      },
      Authors: [],
      Museums: [],
      PicName: '«Трон Людовизи»',
      PicDescription: null,
      ArtifactText: null,
      AuthorText: null,
      MuseumText: null,
      highlight: {
        PicName: [
          '«<em>Трон</em> Людовизи»',
        ],
      },
      type: 'picture',
    },
    {
      Id: 4808,
      IdArtifact: null,
      Name: null,
      PubDate: '2019-01-25T12:17:44.000Z',
      _score: 40335.33,
      IsFragment: false,
      Status: 1,
      URL: 'https://dev.magisteria.ru/data/2016/10/Tron-Lyudovizi-4.jpg',
      MetaInfo: {
        path: '2016/10/',
        'mime-type': 'image/jpeg',
        size: {
          width: 1893,
          height: 814,
        },
        content: {
          l: 'https://dev.magisteria.ru/data/2016/10/Tron-Lyudovizi-4-1366x587.jpg',
          m: 'https://dev.magisteria.ru/data/2016/10/Tron-Lyudovizi-4-768x330.jpg',
          s: 'https://dev.magisteria.ru/data/2016/10/Tron-Lyudovizi-4-360x155.jpg',
        },
        icon: 'https://dev.magisteria.ru/data/2016/10/Tron-Lyudovizi-4-150x150.jpg',
      },
      Authors: [],
      Museums: [],
      PicName: '«Трон Людовизи»',
      PicDescription: null,
      ArtifactText: null,
      AuthorText: null,
      MuseumText: null,
      highlight: {
        PicName: [
          '«<em>Трон</em> Людовизи»',
        ],
      },
      type: 'picture',
    },
    {
      Id: 4809,
      IdArtifact: null,
      Name: null,
      PubDate: '2019-01-25T12:17:44.000Z',
      _score: 40335.33,
      IsFragment: false,
      Status: 1,
      URL: 'https://dev.magisteria.ru/data/2016/10/Tron-Lyudovizi-.-TSentralnyj-relef-levaya-figura.jpg',
      MetaInfo: {
        path: '2016/10/',
        'mime-type': 'image/jpeg',
        size: {
          width: 720,
          height: 1080,
        },
        content: {
          s: 'https://dev.magisteria.ru/data/2016/10/Tron-Lyudovizi-.-TSentralnyj-relef-levaya-figura-360x540.jpg',
        },
        icon: 'https://dev.magisteria.ru/data/2016/10/Tron-Lyudovizi-.-TSentralnyj-relef-levaya-figura-150x150.jpg',
      },
      Authors: [],
      Museums: [],
      PicName: '«Трон Людовизи»',
      PicDescription: 'Центральный рельеф, левая фигура',
      ArtifactText: null,
      AuthorText: null,
      MuseumText: null,
      highlight: {
        PicName: [
          '«<em>Трон</em> Людовизи»',
        ],
      },
      type: 'picture',
    },
    {
      Id: 4810,
      IdArtifact: null,
      Name: null,
      PubDate: '2019-01-25T12:17:44.000Z',
      _score: 40335.33,
      IsFragment: false,
      Status: 1,
      URL: 'https://dev.magisteria.ru/data/2016/10/Tron-Lyudovizi-.-Bokovye-figury.jpg',
      MetaInfo: {
        path: '2016/10/',
        'mime-type': 'image/jpeg',
        size: {
          width: 1824,
          height: 1073,
        },
        content: {
          l: 'https://dev.magisteria.ru/data/2016/10/Tron-Lyudovizi-.-Bokovye-figury-1366x804.jpg',
          m: 'https://dev.magisteria.ru/data/2016/10/Tron-Lyudovizi-.-Bokovye-figury-768x452.jpg',
          s: 'https://dev.magisteria.ru/data/2016/10/Tron-Lyudovizi-.-Bokovye-figury-360x212.jpg',
        },
        icon: 'https://dev.magisteria.ru/data/2016/10/Tron-Lyudovizi-.-Bokovye-figury-150x150.jpg',
      },
      Authors: [],
      Museums: [],
      PicName: '«Трон Людовизи»',
      PicDescription: 'Боковые фигуры',
      ArtifactText: null,
      AuthorText: null,
      MuseumText: null,
      highlight: {
        PicName: [
          '«<em>Трон</em> Людовизи»',
        ],
      },
      type: 'picture',
    },
    {
      Id: 6615,
      IdArtifact: null,
      Name: null,
      PubDate: '2019-01-25T12:17:48.000Z',
      _score: 40335.33,
      IsFragment: false,
      Status: 1,
      URL: 'https://dev.magisteria.ru/data/2017/04/Spasitel-tronnyj.-Hudozhnik-A.N.-Soldatov-rod.-v-1965.jpg',
      MetaInfo: {
        path: '2017/04/',
        'mime-type': 'image/jpeg',
        size: {
          width: 645,
          height: 1080,
        },
        content: {
          s: 'https://dev.magisteria.ru/data/2017/04/Spasitel-tronnyj.-Hudozhnik-A.N.-Soldatov-rod.-v-1965-360x603.jpg',
        },
        icon: 'https://dev.magisteria.ru/data/2017/04/Spasitel-tronnyj.-Hudozhnik-A.N.-Soldatov-rod.-v-1965-150x150.jpg',
      },
      Authors: [],
      Museums: [],
      PicName: 'Спаситель тронный',
      PicDescription: 'Художник – А.Н. Солдатов (род. в 1965)',
      ArtifactText: null,
      AuthorText: null,
      MuseumText: null,
      highlight: {
        PicName: [
          'Спаситель <em>тронный</em>',
        ],
      },
      type: 'picture',
    },
    {
      Id: 4811,
      IdArtifact: null,
      Name: null,
      PubDate: '2019-01-25T12:17:44.000Z',
      _score: 36615.027,
      IsFragment: false,
      Status: 1,
      URL: 'https://dev.magisteria.ru/data/2016/10/Tron-Lyudovizi-.-Avlistka.jpg',
      MetaInfo: {
        path: '2016/10/',
        'mime-type': 'image/jpeg',
        size: {
          width: 919,
          height: 1078,
        },
        content: {
          m: 'https://dev.magisteria.ru/data/2016/10/Tron-Lyudovizi-.-Avlistka-768x901.jpg',
          s: 'https://dev.magisteria.ru/data/2016/10/Tron-Lyudovizi-.-Avlistka-360x422.jpg',
        },
        icon: 'https://dev.magisteria.ru/data/2016/10/Tron-Lyudovizi-.-Avlistka-150x150.jpg',
      },
      Authors: [],
      Museums: [],
      PicName: '«Трон Людовизи». Авлистка',
      PicDescription: null,
      ArtifactText: null,
      AuthorText: null,
      MuseumText: null,
      highlight: {
        PicName: [
          '«<em>Трон</em> Людовизи». Авлистка',
        ],
      },
      type: 'picture',
    },
    {
      Id: 4812,
      IdArtifact: null,
      Name: null,
      PubDate: '2019-01-25T12:17:44.000Z',
      _score: 36615.027,
      IsFragment: false,
      Status: 1,
      URL: 'https://dev.magisteria.ru/data/2016/10/Tron-Lyudovizi-.-ZHritsa.jpg',
      MetaInfo: {
        path: '2016/10/',
        'mime-type': 'image/jpeg',
        size: {
          width: 886,
          height: 1078,
        },
        content: {
          m: 'https://dev.magisteria.ru/data/2016/10/Tron-Lyudovizi-.-ZHritsa-768x934.jpg',
          s: 'https://dev.magisteria.ru/data/2016/10/Tron-Lyudovizi-.-ZHritsa-360x438.jpg',
        },
        icon: 'https://dev.magisteria.ru/data/2016/10/Tron-Lyudovizi-.-ZHritsa-150x150.jpg',
      },
      Authors: [],
      Museums: [],
      PicName: '«Трон Людовизи». Жрица',
      PicDescription: null,
      ArtifactText: null,
      AuthorText: null,
      MuseumText: null,
      highlight: {
        PicName: [
          '«<em>Трон</em> Людовизи». Жрица',
        ],
      },
      type: 'picture',
    },
    {
      Id: 4813,
      IdArtifact: null,
      Name: null,
      PubDate: '2019-01-25T12:17:44.000Z',
      _score: 36615.027,
      IsFragment: false,
      Status: 1,
      URL: 'https://dev.magisteria.ru/data/2016/10/Tron-Lyudovizi-.-Avlistka-2.jpeg',
      MetaInfo: {
        path: '2016/10/',
        'mime-type': 'image/jpeg',
        size: {
          width: 847,
          height: 1024,
        },
        content: {
          m: 'https://dev.magisteria.ru/data/2016/10/Tron-Lyudovizi-.-Avlistka-2-768x928.jpeg',
          s: 'https://dev.magisteria.ru/data/2016/10/Tron-Lyudovizi-.-Avlistka-2-360x435.jpeg',
        },
        icon: 'https://dev.magisteria.ru/data/2016/10/Tron-Lyudovizi-.-Avlistka-2-150x150.jpeg',
      },
      Authors: [],
      Museums: [],
      PicName: '«Трон Людовизи». Авлистка',
      PicDescription: null,
      ArtifactText: null,
      AuthorText: null,
      MuseumText: null,
      highlight: {
        PicName: [
          '«<em>Трон</em> Людовизи». Авлистка',
        ],
      },
      type: 'picture',
    },
    {
      Id: 4788,
      IdArtifact: null,
      Name: null,
      PubDate: '2019-01-25T12:17:44.000Z',
      _score: 35311.82,
      IsFragment: false,
      Status: 1,
      URL: 'https://dev.magisteria.ru/data/2016/10/Apofeoz-Gomera-ok.-225-205-gg.-do-n.e..-Detal-uvenchannyj-Gomer-na-trone.-Mramornyj-votivnyj-relef.-Britanskij-muzej-London.jpg',
      MetaInfo: {
        path: '2016/10/',
        'mime-type': 'image/jpeg',
        size: {
          width: 1008,
          height: 850,
        },
        content: {
          m: 'https://dev.magisteria.ru/data/2016/10/Apofeoz-Gomera-ok.-225-205-gg.-do-n.e..-Detal-uvenchannyj-Gomer-na-trone.-Mramornyj-votivnyj-relef.-Britanskij-muzej-London-768x648.jpg',
          s: 'https://dev.magisteria.ru/data/2016/10/Apofeoz-Gomera-ok.-225-205-gg.-do-n.e..-Detal-uvenchannyj-Gomer-na-trone.-Mramornyj-votivnyj-relef.-Britanskij-muzej-London-360x304.jpg',
        },
        icon: 'https://dev.magisteria.ru/data/2016/10/Apofeoz-Gomera-ok.-225-205-gg.-do-n.e..-Detal-uvenchannyj-Gomer-na-trone.-Mramornyj-votivnyj-relef.-Britanskij-muzej-London-150x150.jpg',
      },
      Authors: [],
      Museums: [],
      PicName: 'Апофеоз Гомера (ок. 225—205 гг. до н.э.)',
      PicDescription: 'Деталь – увенчанный Гомер на троне. Рисунок с мраморного вотивного рельефа. Британский музей, Лондон',
      ArtifactText: null,
      AuthorText: null,
      MuseumText: null,
      highlight: {
        PicDescription: [
          'Деталь – увенчанный Гомер на <em>троне</em>. Рисунок с мраморного вотивного рельефа. Британский музей, Лондон',
        ],
      },
      type: 'picture',
    },
    {
      Id: 5471,
      IdArtifact: null,
      Name: null,
      PubDate: '2019-01-25T12:17:45.000Z',
      _score: 33523.055,
      IsFragment: false,
      Status: 1,
      URL: 'https://dev.magisteria.ru/data/2017/04/Budda-na-trone.-XI-v.-List-iz-rukopisi-Pradzhnyaparamity.-Indiya.-Metropoliten-muzej-Nyu-Jork.jpg',
      MetaInfo: {
        path: '2017/04/',
        'mime-type': 'image/jpeg',
        size: {
          width: 1333,
          height: 778,
        },
        content: {
          m: 'https://dev.magisteria.ru/data/2017/04/Budda-na-trone.-XI-v.-List-iz-rukopisi-Pradzhnyaparamity.-Indiya.-Metropoliten-muzej-Nyu-Jork-768x448.jpg',
          s: 'https://dev.magisteria.ru/data/2017/04/Budda-na-trone.-XI-v.-List-iz-rukopisi-Pradzhnyaparamity.-Indiya.-Metropoliten-muzej-Nyu-Jork-360x210.jpg',
        },
        icon: 'https://dev.magisteria.ru/data/2017/04/Budda-na-trone.-XI-v.-List-iz-rukopisi-Pradzhnyaparamity.-Indiya.-Metropoliten-muzej-Nyu-Jork-150x150.jpg',
      },
      Authors: [],
      Museums: [],
      PicName: 'Будда на троне. Индия, XI в.',
      PicDescription: 'Лист из  рукописи Праджняпарамиты. Метрополитен музей, Нью-Йорк',
      ArtifactText: null,
      AuthorText: null,
      MuseumText: null,
      highlight: {
        PicName: [
          'Будда на <em>троне</em>. Индия, XI в.',
        ],
      },
      type: 'picture',
    },
    {
      Id: 5659,
      IdArtifact: null,
      Name: null,
      PubDate: '2019-01-25T12:17:46.000Z',
      _score: 33523.055,
      IsFragment: false,
      Status: 1,
      URL: 'https://dev.magisteria.ru/data/2017/04/Budda-sidyashhij-na-trone.-XVI-v.-Hudozhestvennyj-muzej-Uolters-Baltimor.jpg',
      MetaInfo: {
        path: '2017/04/',
        'mime-type': 'image/jpeg',
        size: {
          width: 801,
          height: 1034,
        },
        content: {
          m: 'https://dev.magisteria.ru/data/2017/04/Budda-sidyashhij-na-trone.-XVI-v.-Hudozhestvennyj-muzej-Uolters-Baltimor-768x991.jpg',
          s: 'https://dev.magisteria.ru/data/2017/04/Budda-sidyashhij-na-trone.-XVI-v.-Hudozhestvennyj-muzej-Uolters-Baltimor-360x465.jpg',
        },
        icon: 'https://dev.magisteria.ru/data/2017/04/Budda-sidyashhij-na-trone.-XVI-v.-Hudozhestvennyj-muzej-Uolters-Baltimor-150x150.jpg',
      },
      Authors: [],
      Museums: [],
      PicName: 'Будда, сидящий на троне. XVI в.',
      PicDescription: 'Художественный музей Уолтерс, Балтимор',
      ArtifactText: null,
      AuthorText: null,
      MuseumText: null,
      highlight: {
        PicName: [
          'Будда, сидящий на <em>троне</em>. XVI в.',
        ],
      },
      type: 'picture',
    },
    {
      Id: 3389,
      IdArtifact: null,
      Name: null,
      PubDate: '2019-01-25T12:17:41.000Z',
      _score: 33523.055,
      IsFragment: false,
      Status: 1,
      URL: 'https://dev.magisteria.ru/data/2016/12/Madonna-na-trone-so-Sv.Matfeem.-1588.-Hudozhnik-Annibale-Karachchi.jpg',
      MetaInfo: {
        path: '2016/12/',
        'mime-type': 'image/jpeg',
        size: {
          width: 707,
          height: 1080,
        },
        content: {
          s: 'https://dev.magisteria.ru/data/2016/12/Madonna-na-trone-so-Sv.Matfeem.-1588.-Hudozhnik-Annibale-Karachchi-360x550.jpg',
        },
        icon: 'https://dev.magisteria.ru/data/2016/12/Madonna-na-trone-so-Sv.Matfeem.-1588.-Hudozhnik-Annibale-Karachchi-150x150.jpg',
      },
      Authors: [],
      Museums: [],
      PicName: 'Мадонна на троне со Св.Матфеем. 1588',
      PicDescription: 'Художник – Аннибале Караччи (итал. Annibale Carracci, 1560-1609). Картинная галерея, Дрезден',
      ArtifactText: null,
      AuthorText: null,
      MuseumText: null,
      highlight: {
        PicName: [
          'Мадонна на <em>троне</em> со Св.Матфеем. 1588',
        ],
      },
      type: 'picture',
    },
    {
      Id: 5939,
      IdArtifact: null,
      Name: null,
      PubDate: '2019-01-25T12:17:46.000Z',
      _score: 33523.055,
      IsFragment: false,
      Status: 1,
      URL: 'https://dev.magisteria.ru/data/2017/04/Bogomater-na-trone.-857-g.-Sofiya-Konstantinopolskaya.jpg',
      MetaInfo: {
        path: '2017/04/',
        'mime-type': 'image/jpeg',
        size: {
          width: 1024,
          height: 681,
        },
        content: {
          m: 'https://dev.magisteria.ru/data/2017/04/Bogomater-na-trone.-857-g.-Sofiya-Konstantinopolskaya-768x511.jpg',
          s: 'https://dev.magisteria.ru/data/2017/04/Bogomater-na-trone.-857-g.-Sofiya-Konstantinopolskaya-360x239.jpg',
        },
        icon: 'https://dev.magisteria.ru/data/2017/04/Bogomater-na-trone.-857-g.-Sofiya-Konstantinopolskaya-150x150.jpg',
      },
      Authors: [],
      Museums: [],
      PicName: 'Богоматерь на троне. 857 г.',
      PicDescription: 'Храм св. Софии в Константинополе',
      ArtifactText: null,
      AuthorText: null,
      MuseumText: null,
      highlight: {
        PicName: [
          'Богоматерь на <em>троне</em>. 857 г.',
        ],
      },
      type: 'picture',
    },
    {
      Id: 6731,
      IdArtifact: null,
      Name: null,
      PubDate: '2019-01-25T12:17:48.000Z',
      _score: 33523.055,
      IsFragment: false,
      Status: 1,
      URL: 'https://dev.magisteria.ru/data/2017/12/Madonna-na-trone.-Nach.-XIV-v.-Hudozhnik-CHimabue-ital.-Cimabue-1250-1302.-Galereya-Uffitsi-Florentsiya.jpg',
      MetaInfo: {
        path: '2017/12/',
        'mime-type': 'image/jpeg',
        size: {
          width: 616,
          height: 1080,
        },
        content: {
          s: 'https://dev.magisteria.ru/data/2017/12/Madonna-na-trone.-Nach.-XIV-v.-Hudozhnik-CHimabue-ital.-Cimabue-1250-1302.-Galereya-Uffitsi-Florentsiya-360x631.jpg',
        },
        icon: 'https://dev.magisteria.ru/data/2017/12/Madonna-na-trone.-Nach.-XIV-v.-Hudozhnik-CHimabue-ital.-Cimabue-1250-1302.-Galereya-Uffitsi-Florentsiya-150x150.jpg',
      },
      Authors: [],
      Museums: [],
      PicName: 'Мадонна на троне. Нач. XIV в.',
      PicDescription: 'Художник – Чимабуэ (итал. Cimabue, 1250–1302). Галерея Уффици, Флоренция',
      ArtifactText: null,
      AuthorText: null,
      MuseumText: null,
      highlight: {
        PicName: [
          'Мадонна на <em>троне</em>. Нач. XIV в.',
        ],
      },
      type: 'picture',
    },
    {
      Id: 6839,
      IdArtifact: null,
      Name: null,
      PubDate: '2019-01-25T12:17:48.000Z',
      _score: 33523.055,
      IsFragment: false,
      Status: 1,
      URL: 'https://dev.magisteria.ru/data/2017/12/Madonna-na-trone-s-angelami.-1340.-Hudozhnik-Petro-Lorentsetti-ital.-Pietro-Lorenzetti-ok.-1280-1348.-Galereya-Uffitsi-Florentsiya.jpg',
      MetaInfo: {
        path: '2017/12/',
        'mime-type': 'image/jpeg',
        size: {
          width: 800,
          height: 997,
        },
        content: {
          m: 'https://dev.magisteria.ru/data/2017/12/Madonna-na-trone-s-angelami.-1340.-Hudozhnik-Petro-Lorentsetti-ital.-Pietro-Lorenzetti-ok.-1280-1348.-Galereya-Uffitsi-Florentsiya-768x957.jpg',
          s: 'https://dev.magisteria.ru/data/2017/12/Madonna-na-trone-s-angelami.-1340.-Hudozhnik-Petro-Lorentsetti-ital.-Pietro-Lorenzetti-ok.-1280-1348.-Galereya-Uffitsi-Florentsiya-360x449.jpg',
        },
        icon: 'https://dev.magisteria.ru/data/2017/12/Madonna-na-trone-s-angelami.-1340.-Hudozhnik-Petro-Lorentsetti-ital.-Pietro-Lorenzetti-ok.-1280-1348.-Galereya-Uffitsi-Florentsiya-150x150.jpg',
      },
      Authors: [],
      Museums: [],
      PicName: 'Мадонна на троне с ангелами. 1340',
      PicDescription: 'Художник – Пьетро Лоренцетти (итал. Pietro Lorenzetti, ок. 1280–1348). Галерея Уффици, Флоренция',
      ArtifactText: null,
      AuthorText: null,
      MuseumText: null,
      highlight: {
        PicName: [
          'Мадонна на <em>троне</em> с ангелами. 1340',
        ],
      },
      type: 'picture',
    },
    {
      Id: 9443,
      IdArtifact: null,
      Name: null,
      PubDate: '2019-01-25T12:17:53.000Z',
      _score: 33523.055,
      IsFragment: false,
      Status: 1,
      URL: 'https://dev.magisteria.ru/data/2017/10/Galereya-i-tron-Karla-Velikogo.-Ahenskaya-kapella.jpg',
      MetaInfo: {
        path: '2017/10/',
        'mime-type': 'image/jpeg',
        size: {
          width: 1920,
          height: 1080,
        },
        content: {
          l: 'https://dev.magisteria.ru/data/2017/10/Galereya-i-tron-Karla-Velikogo.-Ahenskaya-kapella-1366x768.jpg',
          m: 'https://dev.magisteria.ru/data/2017/10/Galereya-i-tron-Karla-Velikogo.-Ahenskaya-kapella-768x432.jpg',
          s: 'https://dev.magisteria.ru/data/2017/10/Galereya-i-tron-Karla-Velikogo.-Ahenskaya-kapella-360x203.jpg',
        },
        icon: 'https://dev.magisteria.ru/data/2017/10/Galereya-i-tron-Karla-Velikogo.-Ahenskaya-kapella-150x150.jpg',
      },
      Authors: [],
      Museums: [],
      PicName: 'Галерея и трон Карла Великого',
      PicDescription: 'Ахенская капелла',
      ArtifactText: null,
      AuthorText: null,
      MuseumText: null,
      highlight: {
        PicName: [
          'Галерея и <em>трон</em> Карла Великого',
        ],
      },
      type: 'picture',
    },
    {
      Id: 5940,
      IdArtifact: null,
      Name: null,
      PubDate: '2019-01-25T12:17:46.000Z',
      _score: 30912.621,
      IsFragment: false,
      Status: 1,
      URL: 'https://dev.magisteria.ru/data/2017/04/Bogomater-na-trone.-Detal.-857-g.-Sofiya-Konstantinopolskaya.jpg',
      MetaInfo: {
        path: '2017/04/',
        'mime-type': 'image/jpeg',
        size: {
          width: 721,
          height: 998,
        },
        content: {
          s: 'https://dev.magisteria.ru/data/2017/04/Bogomater-na-trone.-Detal.-857-g.-Sofiya-Konstantinopolskaya-360x498.jpg',
        },
        icon: 'https://dev.magisteria.ru/data/2017/04/Bogomater-na-trone.-Detal.-857-g.-Sofiya-Konstantinopolskaya-150x150.jpg',
      },
      Authors: [],
      Museums: [],
      PicName: 'Богоматерь на троне. Деталь. 857 г.',
      PicDescription: 'Храм св. Софии в Константинополе',
      ArtifactText: null,
      AuthorText: null,
      MuseumText: null,
      highlight: {
        PicName: [
          'Богоматерь на <em>троне</em>. Деталь. 857 г.',
        ],
      },
      type: 'picture',
    },
    {
      Id: 6735,
      IdArtifact: null,
      Name: null,
      PubDate: '2019-01-25T12:17:48.000Z',
      _score: 30912.621,
      IsFragment: false,
      Status: 1,
      URL: 'https://dev.magisteria.ru/data/2017/12/Madonna-na-trone-s-angelami.-Ok.-1280.-Hudozhnik-CHimabue-ital.-Cimabue-1250-1302.-Luvr-Parizh.jpg',
      MetaInfo: {
        path: '2017/12/',
        'mime-type': 'image/jpeg',
        size: {
          width: 686,
          height: 1000,
        },
        content: {
          s: 'https://dev.magisteria.ru/data/2017/12/Madonna-na-trone-s-angelami.-Ok.-1280.-Hudozhnik-CHimabue-ital.-Cimabue-1250-1302.-Luvr-Parizh-360x525.jpg',
        },
        icon: 'https://dev.magisteria.ru/data/2017/12/Madonna-na-trone-s-angelami.-Ok.-1280.-Hudozhnik-CHimabue-ital.-Cimabue-1250-1302.-Luvr-Parizh-150x150.jpg',
      },
      Authors: [],
      Museums: [],
      PicName: 'Мадонна на троне с ангелами. Ок. 1280',
      PicDescription: 'Художник – Чимабуэ (итал. Cimabue, 1250–1302). Лувр, Париж',
      ArtifactText: null,
      AuthorText: null,
      MuseumText: null,
      highlight: {
        PicName: [
          'Мадонна на <em>троне</em> с ангелами. Ок. 1280',
        ],
      },
      type: 'picture',
    },
    {
      Id: 2663,
      IdArtifact: null,
      Name: null,
      PubDate: '2019-01-25T12:17:39.000Z',
      _score: 28679.371,
      IsFragment: false,
      Status: 1,
      URL: 'https://dev.magisteria.ru/data/2016/08/Roman_catacombs_IVcentury.jpeg',
      MetaInfo: {
        path: '2016/08/',
        'mime-type': 'image/jpeg',
        size: {
          width: 1262,
          height: 843,
        },
        content: {
          m: 'https://dev.magisteria.ru/data/2016/08/Roman_catacombs_IVcentury-768x513.jpeg',
          s: 'https://dev.magisteria.ru/data/2016/08/Roman_catacombs_IVcentury-360x240.jpeg',
        },
        icon: 'https://dev.magisteria.ru/data/2016/08/Roman_catacombs_IVcentury-150x150.jpeg',
      },
      Authors: [],
      Museums: [],
      PicName: 'Богоматерь с младенцем Христом на троне с избранными святыми',
      PicDescription: 'Римские христианские катакомбы, IV век',
      ArtifactText: null,
      AuthorText: null,
      MuseumText: null,
      highlight: {
        PicName: [
          'Богоматерь с младенцем Христом на <em>троне</em> с избранными святыми',
        ],
      },
      type: 'picture',
    },
    {
      Id: 6779,
      IdArtifact: null,
      Name: null,
      PubDate: '2019-01-25T12:17:48.000Z',
      _score: 28679.371,
      IsFragment: false,
      Status: 1,
      URL: 'https://dev.magisteria.ru/data/2017/12/Maesta.-Fragment.-Bogomater-na-trone.-1308-1311.-Hudozhnik-Duchcho-di-Buoninsenya-ital.-Duccio-di-Buoninsegna-ok.-1255-1319.-Muzej-Opera-del-Duomo-Siena.jpg',
      MetaInfo: {
        path: '2017/12/',
        'mime-type': 'image/jpeg',
        size: {
          width: 966,
          height: 1080,
        },
        content: {
          m: 'https://dev.magisteria.ru/data/2017/12/Maesta.-Fragment.-Bogomater-na-trone.-1308-1311.-Hudozhnik-Duchcho-di-Buoninsenya-ital.-Duccio-di-Buoninsegna-ok.-1255-1319.-Muzej-Opera-del-Duomo-Siena-768x859.jpg',
          s: 'https://dev.magisteria.ru/data/2017/12/Maesta.-Fragment.-Bogomater-na-trone.-1308-1311.-Hudozhnik-Duchcho-di-Buoninsenya-ital.-Duccio-di-Buoninsegna-ok.-1255-1319.-Muzej-Opera-del-Duomo-Siena-360x402.jpg',
        },
        icon: 'https://dev.magisteria.ru/data/2017/12/Maesta.-Fragment.-Bogomater-na-trone.-1308-1311.-Hudozhnik-Duchcho-di-Buoninsenya-ital.-Duccio-di-Buoninsegna-ok.-1255-1319.-Muzej-Opera-del-Duomo-Siena-150x150.jpg',
      },
      Authors: [],
      Museums: [],
      PicName: 'Маэста. Фрагмент. Богоматерь на троне. 1308–1311',
      PicDescription: 'Художник – Дуччо ди Буонинсенья (итал. Duccio di Buoninsegna, ок. 1255–1319). Музей Опера-дель-Дуомо, Сиена',
      ArtifactText: null,
      AuthorText: null,
      MuseumText: null,
      highlight: {
        PicName: [
          'Богоматерь на <em>троне</em>. 1308–1311',
        ],
      },
      type: 'picture',
    },
    {
      Id: 7478,
      IdArtifact: null,
      Name: null,
      PubDate: '2019-01-25T12:17:49.000Z',
      _score: 28679.371,
      IsFragment: false,
      Status: 1,
      URL: 'https://dev.magisteria.ru/data/2018/03/Madonna-na-trone-v-okruzhenii-svyatyh.-1484-1492.-Freska.-Hudozhnik-Pinturikkio-ital.-Pinturicchio-1454-1513.-Kapella-della-Rovere-tserkov-Santa-Mariya-del-Popolo-Rim.jpg',
      MetaInfo: {
        path: '2018/03/',
        'mime-type': 'image/jpeg',
        size: {
          width: 736,
          height: 1010,
        },
        content: {
          s: 'https://dev.magisteria.ru/data/2018/03/Madonna-na-trone-v-okruzhenii-svyatyh.-1484-1492.-Freska.-Hudozhnik-Pinturikkio-ital.-Pinturicchio-1454-1513.-Kapella-della-Rovere-tserkov-Santa-Mariya-del-Popolo-Rim-360x494.jpg',
        },
        icon: 'https://dev.magisteria.ru/data/2018/03/Madonna-na-trone-v-okruzhenii-svyatyh.-1484-1492.-Freska.-Hudozhnik-Pinturikkio-ital.-Pinturicchio-1454-1513.-Kapella-della-Rovere-tserkov-Santa-Mariya-del-Popolo-Rim-150x150.jpg',
      },
      Authors: [],
      Museums: [],
      PicName: 'Мадонна на троне в окружении святых. 1484–1492',
      PicDescription: 'Фреска. Художник – Пинтуриккио (итал. Pinturicchio, 1454–1513). Капелла делла Ровере, церковь Санта-Мария-дель-Пополо, Рим',
      ArtifactText: null,
      AuthorText: null,
      MuseumText: null,
      highlight: {
        PicName: [
          'Мадонна на <em>троне</em> в окружении святых. 1484–1492',
        ],
      },
      type: 'picture',
    },
    {
      Id: 8373,
      IdArtifact: null,
      Name: null,
      PubDate: '2019-01-25T12:17:51.000Z',
      _score: 28679.371,
      IsFragment: false,
      Status: 1,
      URL: 'https://dev.magisteria.ru/data/2017/04/Sidyashhij-na-trone-Majtreya-s-kushanskim-posledovatelem.-II-v.-Tokijskij-natsionalnyj-muzej.jpg',
      MetaInfo: {
        path: '2017/04/',
        'mime-type': 'image/jpeg',
        size: {
          width: 741,
          height: 1080,
        },
        content: {
          s: 'https://dev.magisteria.ru/data/2017/04/Sidyashhij-na-trone-Majtreya-s-kushanskim-posledovatelem.-II-v.-Tokijskij-natsionalnyj-muzej-360x525.jpg',
        },
        icon: 'https://dev.magisteria.ru/data/2017/04/Sidyashhij-na-trone-Majtreya-s-kushanskim-posledovatelem.-II-v.-Tokijskij-natsionalnyj-muzej-150x150.jpg',
      },
      Authors: [],
      Museums: [],
      PicName: 'Сидящий на троне Майтрея с кушанским последователем. II в.',
      PicDescription: 'Токийский национальный музей',
      ArtifactText: null,
      AuthorText: null,
      MuseumText: null,
      highlight: {
        PicName: [
          'Сидящий на <em>троне</em> Майтрея с кушанским последователем. II в.',
        ],
      },
      type: 'picture',
    },
    {
      Id: 9480,
      IdArtifact: null,
      Name: null,
      PubDate: '2019-01-25T12:17:53.000Z',
      _score: 28679.371,
      IsFragment: false,
      Status: 1,
      URL: 'https://dev.magisteria.ru/data/2017/10/Drevo-Iesseevo.-Tron-Premudrosti.-Kon.-XIII-v.-Sad-utesheniya-Natsionalnaya-biblioteka-Frantsii-Parizh.jpg',
      MetaInfo: {
        path: '2017/10/',
        'mime-type': 'image/jpeg',
        size: {
          width: 1920,
          height: 1080,
        },
        content: {
          l: 'https://dev.magisteria.ru/data/2017/10/Drevo-Iesseevo.-Tron-Premudrosti.-Kon.-XIII-v.-Sad-utesheniya-Natsionalnaya-biblioteka-Frantsii-Parizh-1366x768.jpg',
          m: 'https://dev.magisteria.ru/data/2017/10/Drevo-Iesseevo.-Tron-Premudrosti.-Kon.-XIII-v.-Sad-utesheniya-Natsionalnaya-biblioteka-Frantsii-Parizh-768x432.jpg',
          s: 'https://dev.magisteria.ru/data/2017/10/Drevo-Iesseevo.-Tron-Premudrosti.-Kon.-XIII-v.-Sad-utesheniya-Natsionalnaya-biblioteka-Frantsii-Parizh-360x203.jpg',
        },
        icon: 'https://dev.magisteria.ru/data/2017/10/Drevo-Iesseevo.-Tron-Premudrosti.-Kon.-XIII-v.-Sad-utesheniya-Natsionalnaya-biblioteka-Frantsii-Parizh-150x150.jpg',
      },
      Authors: [],
      Museums: [],
      PicName: 'Древо Иессеево. Трон Премудрости. Кон. XIII в.',
      PicDescription: '«Сад утешения». Национальная библиотека Франции, Париж',
      ArtifactText: null,
      AuthorText: null,
      MuseumText: null,
      highlight: {
        PicName: [
          '<em>Трон</em> Премудрости. Кон. XIII в.',
        ],
      },
      type: 'picture',
    },
    {
      Id: 4805,
      IdArtifact: null,
      Name: null,
      PubDate: '2019-01-25T12:17:44.000Z',
      _score: 26747.05,
      IsFragment: false,
      Status: 1,
      URL: 'https://dev.magisteria.ru/data/2016/10/Tak-nazyvaemyj-Tron-Lyudovizi-.-Ok.-460-g.-do-n.e.-Mramor-s-o.-Tasos.-Najden-v-1887-g.-na-Ville-Lyudovizi-v-prigorode-Rima.-Natsionalnyj-muzej-Rima-1.jpg',
      MetaInfo: {
        path: '2016/10/',
        'mime-type': 'image/jpeg',
        size: {
          width: 1280,
          height: 886,
        },
        content: {
          m: 'https://dev.magisteria.ru/data/2016/10/Tak-nazyvaemyj-Tron-Lyudovizi-.-Ok.-460-g.-do-n.e.-Mramor-s-o.-Tasos.-Najden-v-1887-g.-na-Ville-Lyudovizi-v-prigorode-Rima.-Natsionalnyj-muzej-Rima-1-768x532.jpg',
          s: 'https://dev.magisteria.ru/data/2016/10/Tak-nazyvaemyj-Tron-Lyudovizi-.-Ok.-460-g.-do-n.e.-Mramor-s-o.-Tasos.-Najden-v-1887-g.-na-Ville-Lyudovizi-v-prigorode-Rima.-Natsionalnyj-muzej-Rima-1-360x249.jpg',
        },
        icon: 'https://dev.magisteria.ru/data/2016/10/Tak-nazyvaemyj-Tron-Lyudovizi-.-Ok.-460-g.-do-n.e.-Mramor-s-o.-Tasos.-Najden-v-1887-g.-na-Ville-Lyudovizi-v-prigorode-Rima.-Natsionalnyj-muzej-Rima-1-150x150.jpg',
      },
      Authors: [],
      Museums: [],
      PicName: 'Так называемый «Трон Людовизи». Ок. 460 г. до н.э.',
      PicDescription: 'Мрамор с о. Тасос. Найден в 1887 г. на Вилле Людовизи, в пригороде Рима. Национальный музей Рима',
      ArtifactText: null,
      AuthorText: null,
      MuseumText: null,
      highlight: {
        PicName: [
          'Так называемый «<em>Трон</em> Людовизи». Ок. 460 г. до н.э.',
        ],
      },
      type: 'picture',
    },
    {
      Id: 5822,
      IdArtifact: null,
      Name: null,
      PubDate: '2019-01-25T12:17:46.000Z',
      _score: 26747.05,
      IsFragment: false,
      Status: 1,
      URL: 'https://dev.magisteria.ru/data/2017/04/Bazilika-Konstantina-v-Trire.-Tronnyj-zal.-310-g..jpg',
      MetaInfo: {
        path: '2017/04/',
        'mime-type': 'image/jpeg',
        size: {
          width: 1524,
          height: 1070,
        },
        content: {
          l: 'https://dev.magisteria.ru/data/2017/04/Bazilika-Konstantina-v-Trire.-Tronnyj-zal.-310-g.-1366x959.jpg',
          m: 'https://dev.magisteria.ru/data/2017/04/Bazilika-Konstantina-v-Trire.-Tronnyj-zal.-310-g.-768x539.jpg',
          s: 'https://dev.magisteria.ru/data/2017/04/Bazilika-Konstantina-v-Trire.-Tronnyj-zal.-310-g.-360x253.jpg',
        },
        icon: 'https://dev.magisteria.ru/data/2017/04/Bazilika-Konstantina-v-Trire.-Tronnyj-zal.-310-g.-150x150.jpg',
      },
      Authors: [],
      Museums: [],
      PicName: 'Базилика Константина в Трире. Тронный зал. 310 г.',
      PicDescription: null,
      ArtifactText: null,
      AuthorText: null,
      MuseumText: null,
      highlight: {
        PicName: [
          '<em>Тронный</em> зал. 310 г.',
        ],
      },
      type: 'picture',
    },
    {
      Id: 5943,
      IdArtifact: null,
      Name: null,
      PubDate: '2019-01-25T12:17:46.000Z',
      _score: 26747.05,
      IsFragment: false,
      Status: 1,
      URL: 'https://dev.magisteria.ru/data/2017/04/Imperator-Lev-VI-Mudryj-pered-tronom-Hrista.-IX-v.-Mozaiki-sv.-Sofii-Konstantinopolskoj.jpg',
      MetaInfo: {
        path: '2017/04/',
        'mime-type': 'image/jpeg',
        size: {
          width: 1024,
          height: 683,
        },
        content: {
          m: 'https://dev.magisteria.ru/data/2017/04/Imperator-Lev-VI-Mudryj-pered-tronom-Hrista.-IX-v.-Mozaiki-sv.-Sofii-Konstantinopolskoj-768x512.jpg',
          s: 'https://dev.magisteria.ru/data/2017/04/Imperator-Lev-VI-Mudryj-pered-tronom-Hrista.-IX-v.-Mozaiki-sv.-Sofii-Konstantinopolskoj-360x240.jpg',
        },
        icon: 'https://dev.magisteria.ru/data/2017/04/Imperator-Lev-VI-Mudryj-pered-tronom-Hrista.-IX-v.-Mozaiki-sv.-Sofii-Konstantinopolskoj-150x150.jpg',
      },
      Authors: [],
      Museums: [],
      PicName: 'Император Лев VI Мудрый перед троном Христа. IX в.',
      PicDescription: 'Мозаики храма св. Софии Константинопольской',
      ArtifactText: null,
      AuthorText: null,
      MuseumText: null,
      highlight: {
        PicName: [
          'Император Лев VI Мудрый перед <em>троном</em> Христа. IX в.',
        ],
      },
      type: 'picture',
    },
    {
      Id: 5288,
      IdArtifact: null,
      Name: null,
      PubDate: '2019-01-25T12:17:45.000Z',
      _score: 25058.688,
      IsFragment: false,
      Status: 1,
      URL: 'https://dev.magisteria.ru/data/2017/04/Napadenie-demonov-Mara-na-Buddu-simvol-Buddy-tron.-II-v.-Muzej-Gime-Parizh.jpg',
      MetaInfo: {
        path: '2017/04/',
        'mime-type': 'image/jpeg',
        size: {
          width: 528,
          height: 779,
        },
        content: {
          s: 'https://dev.magisteria.ru/data/2017/04/Napadenie-demonov-Mara-na-Buddu-simvol-Buddy-tron.-II-v.-Muzej-Gime-Parizh-360x531.jpg',
        },
        icon: 'https://dev.magisteria.ru/data/2017/04/Napadenie-demonov-Mara-na-Buddu-simvol-Buddy-tron.-II-v.-Muzej-Gime-Parizh-150x150.jpg',
      },
      Authors: [],
      Museums: [],
      PicName: 'Нападение демонов Мара на Будду (символ Будды – трон). II в.',
      PicDescription: 'Музей Гиме, Париж',
      ArtifactText: null,
      AuthorText: null,
      MuseumText: null,
      highlight: {
        PicName: [
          'Нападение демонов Мара на Будду (символ Будды – <em>трон</em>). II в.',
        ],
      },
      type: 'picture',
    },
    {
      Id: 8362,
      IdArtifact: null,
      Name: null,
      PubDate: '2019-01-25T12:17:51.000Z',
      _score: 25058.688,
      IsFragment: false,
      Status: 1,
      URL: 'https://dev.magisteria.ru/data/2017/04/Almaznyj-tron-postroennyj-Ashokoj-v-hrame-Mahabodhi-v-Bodh-Gaya.jpg',
      MetaInfo: {
        path: '2017/04/',
        'mime-type': 'image/jpeg',
        size: {
          width: 1320,
          height: 1080,
        },
        content: {
          m: 'https://dev.magisteria.ru/data/2017/04/Almaznyj-tron-postroennyj-Ashokoj-v-hrame-Mahabodhi-v-Bodh-Gaya-768x628.jpg',
          s: 'https://dev.magisteria.ru/data/2017/04/Almaznyj-tron-postroennyj-Ashokoj-v-hrame-Mahabodhi-v-Bodh-Gaya-360x295.jpg',
        },
        icon: 'https://dev.magisteria.ru/data/2017/04/Almaznyj-tron-postroennyj-Ashokoj-v-hrame-Mahabodhi-v-Bodh-Gaya-150x150.jpg',
      },
      Authors: [],
      Museums: [],
      PicName: '«Алмазный трон», построенный Ашокой в храме Махабодхи в Бодх-Гая',
      PicDescription: null,
      ArtifactText: null,
      AuthorText: null,
      MuseumText: null,
      highlight: {
        PicName: [
          '«Алмазный <em>трон</em>», построенный Ашокой в храме Махабодхи в Бодх-Гая',
        ],
      },
      type: 'picture',
    },
    {
      Id: 14067,
      IdArtifact: null,
      Name: null,
      PubDate: '2019-01-25T12:18:02.000Z',
      _score: 25058.688,
      IsFragment: false,
      Status: 1,
      URL: 'https://dev.magisteria.ru/data/2018/05/Prorok-Muhammad-na-trone-okruzhennyj-angelami-i-spodvizhnikami.-Nach.-XIV-v.-Miniatyura-iz-Knigi-tsarej-.-Smitsonovskij-institut-Vashington.jpg',
      MetaInfo: {
        path: '2018/05/',
        'mime-type': 'image/jpeg',
        size: {
          width: 940,
          height: 893,
        },
        content: {
          m: 'https://dev.magisteria.ru/data/2018/05/Prorok-Muhammad-na-trone-okruzhennyj-angelami-i-spodvizhnikami.-Nach.-XIV-v.-Miniatyura-iz-Knigi-tsarej-.-Smitsonovskij-institut-Vashington-768x730.jpg',
          s: 'https://dev.magisteria.ru/data/2018/05/Prorok-Muhammad-na-trone-okruzhennyj-angelami-i-spodvizhnikami.-Nach.-XIV-v.-Miniatyura-iz-Knigi-tsarej-.-Smitsonovskij-institut-Vashington-360x342.jpg',
        },
        icon: 'https://dev.magisteria.ru/data/2018/05/Prorok-Muhammad-na-trone-okruzhennyj-angelami-i-spodvizhnikami.-Nach.-XIV-v.-Miniatyura-iz-Knigi-tsarej-.-Smitsonovskij-institut-Vashington-150x150.jpg',
      },
      Authors: [],
      Museums: [],
      PicName: 'Пророк Мухаммад на троне, окруженный ангелами и сподвижниками. Нач. XIV в.',
      PicDescription: 'Миниатюра из «Книги царей». Смитсоновский институт, Вашингтон',
      ArtifactText: null,
      AuthorText: null,
      MuseumText: null,
      highlight: {
        PicName: [
          'Пророк Мухаммад на <em>троне</em>, окруженный ангелами и сподвижниками. Нач. XIV в.',
        ],
      },
      type: 'picture',
    },
    {
      Id: 11286,
      IdArtifact: null,
      Name: null,
      PubDate: '2019-01-25T12:17:57.000Z',
      _score: 23570.812,
      IsFragment: false,
      Status: 1,
      URL: 'https://dev.magisteria.ru/data/2018/02/Dvojnoj-tron-tsarej-Ivana-Alekseevicha-i-Petra-Alekseevicha.-1682-1684.-Masterskie-Moskovskogo-Kremlya.-Serebro-derevo-lite-chekanka-rezba-gravirovka-zolochenie.-Muzei-Moskovskogo-Kremlya.jpg',
      MetaInfo: {
        path: '2018/02/',
        'mime-type': 'image/jpeg',
        size: {
          width: 602,
          height: 768,
        },
        content: {
          s: 'https://dev.magisteria.ru/data/2018/02/Dvojnoj-tron-tsarej-Ivana-Alekseevicha-i-Petra-Alekseevicha.-1682-1684.-Masterskie-Moskovskogo-Kremlya.-Serebro-derevo-lite-chekanka-rezba-gravirovka-zolochenie.-Muzei-Moskovskogo-Kremlya-360x459.jpg',
        },
        icon: 'https://dev.magisteria.ru/data/2018/02/Dvojnoj-tron-tsarej-Ivana-Alekseevicha-i-Petra-Alekseevicha.-1682-1684.-Masterskie-Moskovskogo-Kremlya.-Serebro-derevo-lite-chekanka-rezba-gravirovka-zolochenie.-Muzei-Moskovskogo-Kremlya-150x150.jpg',
      },
      Authors: [],
      Museums: [],
      PicName: 'Двойной трон царей Ивана Алексеевича и Петра Алексеевича. 1682–1684',
      PicDescription: 'Мастерские Московского Кремля. Серебро, дерево, литье, чеканка, резьба, гравировка, золочение. Музеи Московского Кремля',
      ArtifactText: null,
      AuthorText: null,
      MuseumText: null,
      highlight: {
        PicName: [
          'Двойной <em>трон</em> царей Ивана Алексеевича и Петра Алексеевича. 1682–1684',
        ],
      },
      type: 'picture',
    },
    {
      Id: 5011,
      IdArtifact: null,
      Name: null,
      PubDate: '2019-01-25T12:17:44.000Z',
      _score: 22249.723,
      IsFragment: false,
      Status: 1,
      URL: 'https://dev.magisteria.ru/data/2017/04/Budda-Majtreya-sidyashhij-na-trone-po-evropejski-s-posledovatelem-iz-Kushana.-II-vek-Gandhara.jpg',
      MetaInfo: {
        path: '2017/04/',
        'mime-type': 'image/jpeg',
        size: {
          width: 739,
          height: 1078,
        },
        content: {
          s: 'https://dev.magisteria.ru/data/2017/04/Budda-Majtreya-sidyashhij-na-trone-po-evropejski-s-posledovatelem-iz-Kushana.-II-vek-Gandhara-360x525.jpg',
        },
        icon: 'https://dev.magisteria.ru/data/2017/04/Budda-Majtreya-sidyashhij-na-trone-po-evropejski-s-posledovatelem-iz-Kushana.-II-vek-Gandhara-150x150.jpg',
      },
      Authors: [],
      Museums: [],
      PicName: 'Будда-Майтрея, сидящий на троне «по-европейски», с последователем из Кушана. II век, Гандхара',
      PicDescription: null,
      ArtifactText: null,
      AuthorText: null,
      MuseumText: null,
      highlight: {
        PicName: [
          'Будда-Майтрея, сидящий на <em>троне</em> «по-европейски», с последователем из Кушана. II век, Гандхара',
        ],
      },
      type: 'picture',
    },
    {
      Id: 12388,
      IdArtifact: null,
      Name: null,
      PubDate: '2019-01-25T12:17:59.000Z',
      _score: 22249.723,
      IsFragment: false,
      Status: 1,
      URL: 'https://dev.magisteria.ru/data/2018/04/Portret-imperatora-YUnchzhena-Ajsingyoro-Inchzhen-1678-1735-pravil-s-1722-na-trone.-Neizvestnyj-pridvornyj-hudozhnik.-Gugun-Pekin.jpg',
      MetaInfo: {
        path: '2018/04/',
        'mime-type': 'image/jpeg',
        size: {
          width: 690,
          height: 1073,
        },
        content: {
          s: 'https://dev.magisteria.ru/data/2018/04/Portret-imperatora-YUnchzhena-Ajsingyoro-Inchzhen-1678-1735-pravil-s-1722-na-trone.-Neizvestnyj-pridvornyj-hudozhnik.-Gugun-Pekin-360x560.jpg',
        },
        icon: 'https://dev.magisteria.ru/data/2018/04/Portret-imperatora-YUnchzhena-Ajsingyoro-Inchzhen-1678-1735-pravil-s-1722-na-trone.-Neizvestnyj-pridvornyj-hudozhnik.-Gugun-Pekin-150x150.jpg',
      },
      Authors: [],
      Museums: [],
      PicName: 'Портрет императора Юнчжэна (Айсиньгёро Иньчжэнь, 1678–1735, правил с 1722) на троне',
      PicDescription: 'Неизвестный придворный художник. Гугун, Пекин',
      ArtifactText: null,
      AuthorText: null,
      MuseumText: null,
      highlight: {
        PicName: [
          'Портрет императора Юнчжэна (Айсиньгёро Иньчжэнь, 1678–1735, правил с 1722) на <em>троне</em>',
        ],
      },
      type: 'picture',
    },
    {
      Id: 13675,
      IdArtifact: null,
      Name: null,
      PubDate: '2019-01-25T12:18:01.000Z',
      _score: 21068.867,
      IsFragment: false,
      Status: 1,
      URL: 'https://dev.magisteria.ru/data/2018/05/Kamennyj-tron-obnaruzhennyj-pri-raskopkah-sinagogi-v-Horazine-v-1926-g.-III-IV-vv.-Sinagoga-v-Horazine-Izrail.jpg',
      MetaInfo: {
        path: '2018/05/',
        'mime-type': 'image/jpeg',
        size: {
          width: 768,
          height: 1024,
        },
        content: {
          m: 'https://dev.magisteria.ru/data/2018/05/Kamennyj-tron-obnaruzhennyj-pri-raskopkah-sinagogi-v-Horazine-v-1926-g.-III-IV-vv.-Sinagoga-v-Horazine-Izrail-768x1024.jpg',
          s: 'https://dev.magisteria.ru/data/2018/05/Kamennyj-tron-obnaruzhennyj-pri-raskopkah-sinagogi-v-Horazine-v-1926-g.-III-IV-vv.-Sinagoga-v-Horazine-Izrail-360x480.jpg',
        },
        icon: 'https://dev.magisteria.ru/data/2018/05/Kamennyj-tron-obnaruzhennyj-pri-raskopkah-sinagogi-v-Horazine-v-1926-g.-III-IV-vv.-Sinagoga-v-Horazine-Izrail-150x150.jpg',
      },
      Authors: [],
      Museums: [],
      PicName: 'Каменный трон, обнаруженный при раскопках синагоги в Хоразине в 1926 г. III–IV вв.',
      PicDescription: 'Синагога в Хоразине, Израиль',
      ArtifactText: null,
      AuthorText: null,
      MuseumText: null,
      highlight: {
        PicName: [
          'Каменный <em>трон</em>, обнаруженный при раскопках синагоги в Хоразине в 1926 г. III–IV вв.',
        ],
      },
      type: 'picture',
    },
    {
      Id: 12392,
      IdArtifact: null,
      Name: null,
      PubDate: '2019-01-25T12:17:59.000Z',
      _score: 19047.086,
      IsFragment: false,
      Status: 1,
      URL: 'https://dev.magisteria.ru/data/2018/04/Paradnyj-portret-imperatora-TSyanluna-Ajsingyoro-Hunli-1711-1799-pravil-1735-1796-na-trone.-1736.-Hudozhnik-Dzhuzeppe-Kastilone-ital.-Giuseppe-Castiglione-1688-1766.-Gugun-Pekin.jpg',
      MetaInfo: {
        path: '2018/04/',
        'mime-type': 'image/jpeg',
        size: {
          width: 763,
          height: 1024,
        },
        content: {
          s: 'https://dev.magisteria.ru/data/2018/04/Paradnyj-portret-imperatora-TSyanluna-Ajsingyoro-Hunli-1711-1799-pravil-1735-1796-na-trone.-1736.-Hudozhnik-Dzhuzeppe-Kastilone-ital.-Giuseppe-Castiglione-1688-1766.-Gugun-Pekin-360x483.jpg',
        },
        icon: 'https://dev.magisteria.ru/data/2018/04/Paradnyj-portret-imperatora-TSyanluna-Ajsingyoro-Hunli-1711-1799-pravil-1735-1796-na-trone.-1736.-Hudozhnik-Dzhuzeppe-Kastilone-ital.-Giuseppe-Castiglione-1688-1766.-Gugun-Pekin-150x150.jpg',
      },
      Authors: [],
      Museums: [],
      PicName: 'Парадный портрет императора Цяньлуна (Айсиньгёро Хунли, 1711–1799, правил 1735–1796) на троне. 1736',
      PicDescription: 'Художник – Джузеппе Кастильоне (итал. Giuseppe Castiglione, 1688–1766). Гугун, Пекин',
      ArtifactText: null,
      AuthorText: null,
      MuseumText: null,
      highlight: {
        PicName: [
          'Парадный портрет императора Цяньлуна (Айсиньгёро Хунли, 1711–1799, правил 1735–1796) на <em>троне</em>. 1736',
        ],
      },
      type: 'picture',
    },
    {
      Id: 9483,
      IdArtifact: null,
      Name: null,
      PubDate: '2019-01-25T12:17:53.000Z',
      _score: 14258.289,
      IsFragment: false,
      Status: 1,
      URL: 'https://dev.magisteria.ru/data/2017/10/Tron-Premudrosti.-Kon.-XIII-v.-Sad-utesheniya-Natsionalnaya-biblioteka-Frantsii-Parizh.-TSentralnyj-portal-Strasburgskogo-sobora.-XIII-XV-vv.-Frantsiya.jpg',
      MetaInfo: {
        path: '2017/10/',
        'mime-type': 'image/jpeg',
        size: {
          width: 1920,
          height: 1080,
        },
        content: {
          l: 'https://dev.magisteria.ru/data/2017/10/Tron-Premudrosti.-Kon.-XIII-v.-Sad-utesheniya-Natsionalnaya-biblioteka-Frantsii-Parizh.-TSentralnyj-portal-Strasburgskogo-sobora.-XIII-XV-vv.-Frantsiya-1366x768.jpg',
          m: 'https://dev.magisteria.ru/data/2017/10/Tron-Premudrosti.-Kon.-XIII-v.-Sad-utesheniya-Natsionalnaya-biblioteka-Frantsii-Parizh.-TSentralnyj-portal-Strasburgskogo-sobora.-XIII-XV-vv.-Frantsiya-768x432.jpg',
          s: 'https://dev.magisteria.ru/data/2017/10/Tron-Premudrosti.-Kon.-XIII-v.-Sad-utesheniya-Natsionalnaya-biblioteka-Frantsii-Parizh.-TSentralnyj-portal-Strasburgskogo-sobora.-XIII-XV-vv.-Frantsiya-360x203.jpg',
        },
        icon: 'https://dev.magisteria.ru/data/2017/10/Tron-Premudrosti.-Kon.-XIII-v.-Sad-utesheniya-Natsionalnaya-biblioteka-Frantsii-Parizh.-TSentralnyj-portal-Strasburgskogo-sobora.-XIII-XV-vv.-Frantsiya-150x150.jpg',
      },
      Authors: [],
      Museums: [],
      PicName: 'Слева: Трон Премудрости. Кон. XIII в. «Сад утешения» Национальная библиотека Франции, Париж. Справа: Центральный портал Страсбургского собора. XIII–XV вв. Франция',
      PicDescription: null,
      ArtifactText: null,
      AuthorText: null,
      MuseumText: null,
      highlight: {
        PicName: [
          'Слева: <em>Трон</em> Премудрости. Кон. XIII в. «Сад утешения» Национальная библиотека Франции, Париж. Справа: Центральный портал Страсбургского собора. XIII–XV вв. Франция',
        ],
      },
      type: 'picture',
    },
    {
      Id: 9588,
      IdArtifact: null,
      Name: null,
      PubDate: '2019-01-25T12:17:54.000Z',
      _score: 14258.289,
      IsFragment: false,
      Status: 1,
      URL: 'https://dev.magisteria.ru/data/2017/10/Hristos-na-trone.-Ok.-400.-Mozaika.-Bazilika-Santa-Pudentsiana-Rim.-Muchenik.-V-v.-Mozaika.-Baptisterij-San-Dzhovanni-in-Fonte-Neapol.jpg',
      MetaInfo: {
        path: '2017/10/',
        'mime-type': 'image/jpeg',
        size: {
          width: 1920,
          height: 1080,
        },
        content: {
          l: 'https://dev.magisteria.ru/data/2017/10/Hristos-na-trone.-Ok.-400.-Mozaika.-Bazilika-Santa-Pudentsiana-Rim.-Muchenik.-V-v.-Mozaika.-Baptisterij-San-Dzhovanni-in-Fonte-Neapol-1366x768.jpg',
          m: 'https://dev.magisteria.ru/data/2017/10/Hristos-na-trone.-Ok.-400.-Mozaika.-Bazilika-Santa-Pudentsiana-Rim.-Muchenik.-V-v.-Mozaika.-Baptisterij-San-Dzhovanni-in-Fonte-Neapol-768x432.jpg',
          s: 'https://dev.magisteria.ru/data/2017/10/Hristos-na-trone.-Ok.-400.-Mozaika.-Bazilika-Santa-Pudentsiana-Rim.-Muchenik.-V-v.-Mozaika.-Baptisterij-San-Dzhovanni-in-Fonte-Neapol-360x203.jpg',
        },
        icon: 'https://dev.magisteria.ru/data/2017/10/Hristos-na-trone.-Ok.-400.-Mozaika.-Bazilika-Santa-Pudentsiana-Rim.-Muchenik.-V-v.-Mozaika.-Baptisterij-San-Dzhovanni-in-Fonte-Neapol-150x150.jpg',
      },
      Authors: [],
      Museums: [],
      PicName: 'Слева: Христос на троне. Ок. 400. Мозаика. Базилика Санта Пуденциана, Рим. Справа: Мученик. V в. Мозаика. Баптистерий Сан Джованни ин Фонте, Неаполь',
      PicDescription: null,
      ArtifactText: null,
      AuthorText: null,
      MuseumText: null,
      highlight: {
        PicName: [
          'Слева: Христос на <em>троне</em>. Ок. 400. Мозаика. Базилика Санта Пуденциана, Рим. Справа: Мученик. V в. Мозаика. Баптистерий Сан Джованни ин Фонте, Неаполь',
        ],
      },
      type: 'picture',
    },
  ],
  count: 38,
};

export default searchResult;
