import { ImageDbInfo } from '#types/images';

const lessonImages: Array<ImageDbInfo> = [
  {
    Id: 4720,
    ResType: 'P',
    FileName: '2016/09/Rembrandt-Abraham-Sacrifice-1655-big1.jpg',
    ResLanguageId: null,
    ShowInGalery: true,
    Language: null,
    Name: 'Жертвоприношение Авраама (1655)',
    Description: 'Офорт. Художник - Рембрандт ван Рейн (1606 — 1669)',
    AltAttribute: null,
    MetaData: '{"path":"2016/09/","mime-type":"image/jpeg","size":{"width":854,"height":1024},"content":{"m":"Rembrandt-Abraham-Sacrifice-1655-big1-768x921.jpg","s":"Rembrandt-Abraham-Sacrifice-1655-big1-360x432.jpg"},"icon":"Rembrandt-Abraham-Sacrifice-1655-big1-150x150.jpg"}',
    ArtifactText: null,
    AuthorText: null,
    MuseumText: null,
    Descriptor: null,
    IsFragment: false,
    Status: 1,
    IsNew: true,
    LinkTypeId: null,
    TimeCr: '2019-01-25T12:17:44.000Z',
  },
  {
    Id: 4721,
    ResType: 'P',
    FileName: '2016/09/Rembrandt-ZHertvoprinoshenie-Avraama-1635-Ermitazh.jpg',
    ResLanguageId: null,
    ShowInGalery: true,
    Language: null,
    Name: 'Жертвоприношение Авраама (1635)',
    Description: 'Эрмитаж. Художник - Рембрандт ван Рейн (1606 — 1669)',
    AltAttribute: null,
    MetaData: '{"path":"2016/09/","mime-type":"image/jpeg","size":{"width":696,"height":1024},"content":{"s":"Rembrandt-ZHertvoprinoshenie-Avraama-1635-Ermitazh-360x530.jpg"},"icon":"Rembrandt-ZHertvoprinoshenie-Avraama-1635-Ermitazh-150x150.jpg"}',
    ArtifactText: null,
    AuthorText: null,
    MuseumText: null,
    Descriptor: null,
    IsFragment: false,
    Status: 1,
    IsNew: true,
    LinkTypeId: null,
    TimeCr: '2019-01-25T12:17:44.000Z',
  },
  {
    Id: 4722,
    ResType: 'P',
    FileName: '2016/09/Vat.gr_.1209_0019_pa_0015_l.jpg',
    ResLanguageId: null,
    ShowInGalery: true,
    Language: null,
    Name: 'Библия, Бытие, Глава 22',
    Description: 'Ватиканский кодекс 1209, середина IV века (лат. Codex Vaticanus)',
    AltAttribute: null,
    MetaData: '{"path":"2016/09/","mime-type":"image/jpeg","size":{"width":1015,"height":1024},"content":{"m":"Vat.gr_.1209_0019_pa_0015_l-768x775.jpg","s":"Vat.gr_.1209_0019_pa_0015_l-360x363.jpg"},"icon":"Vat.gr_.1209_0019_pa_0015_l-150x150.jpg"}',
    ArtifactText: null,
    AuthorText: null,
    MuseumText: null,
    Descriptor: null,
    IsFragment: false,
    Status: 1,
    IsNew: true,
    LinkTypeId: null,
    TimeCr: '2019-01-25T12:17:44.000Z',
  },
  {
    Id: 4723,
    ResType: 'P',
    FileName: '2016/09/Bytie-22-1-3-rus.png',
    ResLanguageId: null,
    ShowInGalery: true,
    Language: null,
    Name: '',
    Description: null,
    AltAttribute: 'bytie-22-1-3-rus',
    MetaData: '{"path":"2016/09/","mime-type":"image/png","size":{"width":768,"height":765},"content":{"m":"Bytie-22-1-3-rus-768x765.png","s":"Bytie-22-1-3-rus-360x359.png"},"icon":"Bytie-22-1-3-rus-150x150.png"}',
    ArtifactText: null,
    AuthorText: null,
    MuseumText: null,
    Descriptor: null,
    IsFragment: false,
    Status: 1,
    IsNew: true,
    LinkTypeId: null,
    TimeCr: '2019-01-25T12:17:44.000Z',
  },
  {
    Id: 4724,
    ResType: 'P',
    FileName: '2016/09/Bytie-22-4-7-rus.png',
    ResLanguageId: null,
    ShowInGalery: true,
    Language: null,
    Name: '',
    Description: null,
    AltAttribute: 'bytie-22-4-7-rus',
    MetaData: '{"path":"2016/09/","mime-type":"image/png","size":{"width":768,"height":765},"content":{"m":"Bytie-22-4-7-rus-768x765.png","s":"Bytie-22-4-7-rus-360x359.png"},"icon":"Bytie-22-4-7-rus-150x150.png"}',
    ArtifactText: null,
    AuthorText: null,
    MuseumText: null,
    Descriptor: null,
    IsFragment: false,
    Status: 1,
    IsNew: true,
    LinkTypeId: null,
    TimeCr: '2019-01-25T12:17:44.000Z',
  },
  {
    Id: 4725,
    ResType: 'P',
    FileName: '2016/09/Msr_22-8.png',
    ResLanguageId: null,
    ShowInGalery: true,
    Language: null,
    Name: '',
    Description: null,
    AltAttribute: 'msr_22-8',
    MetaData: '{"path":"2016/09/","mime-type":"image/png","size":{"width":768,"height":765},"content":{"m":"Msr_22-8-768x765.png","s":"Msr_22-8-360x359.png"},"icon":"Msr_22-8-150x150.png"}',
    ArtifactText: null,
    AuthorText: null,
    MuseumText: null,
    Descriptor: null,
    IsFragment: false,
    Status: 1,
    IsNew: true,
    LinkTypeId: null,
    TimeCr: '2019-01-25T12:17:44.000Z',
  },
  {
    Id: 4726,
    ResType: 'P',
    FileName: '2016/09/Sept_22-92.png',
    ResLanguageId: null,
    ShowInGalery: true,
    Language: null,
    Name: '',
    Description: null,
    AltAttribute: 'sept_22-9',
    MetaData: '{"path":"2016/09/","mime-type":"image/png","size":{"width":768,"height":765},"content":{"m":"Sept_22-92-768x765.png","s":"Sept_22-92-360x359.png"},"icon":"Sept_22-92-150x150.png"}',
    ArtifactText: null,
    AuthorText: null,
    MuseumText: null,
    Descriptor: null,
    IsFragment: false,
    Status: 1,
    IsNew: true,
    LinkTypeId: null,
    TimeCr: '2019-01-25T12:17:44.000Z',
  },
  {
    Id: 4727,
    ResType: 'P',
    FileName: '2016/09/Bytie-22-8-11-rus.png',
    ResLanguageId: null,
    ShowInGalery: true,
    Language: null,
    Name: '',
    Description: null,
    AltAttribute: 'bytie-22-8-11-rus',
    MetaData: '{"path":"2016/09/","mime-type":"image/png","size":{"width":768,"height":765},"content":{"m":"Bytie-22-8-11-rus-768x765.png","s":"Bytie-22-8-11-rus-360x359.png"},"icon":"Bytie-22-8-11-rus-150x150.png"}',
    ArtifactText: null,
    AuthorText: null,
    MuseumText: null,
    Descriptor: null,
    IsFragment: false,
    Status: 1,
    IsNew: true,
    LinkTypeId: null,
    TimeCr: '2019-01-25T12:17:44.000Z',
  },
  {
    Id: 4728,
    ResType: 'P',
    FileName: '2016/09/Bytie-22-1213-rus.png',
    ResLanguageId: null,
    ShowInGalery: true,
    Language: null,
    Name: '',
    Description: null,
    AltAttribute: 'bytie-22-12-13-rus',
    MetaData: '{"path":"2016/09/","mime-type":"image/png","size":{"width":768,"height":765},"content":{"m":"Bytie-22-1213-rus-768x765.png","s":"Bytie-22-1213-rus-360x359.png"},"icon":"Bytie-22-1213-rus-150x150.png"}',
    ArtifactText: null,
    AuthorText: null,
    MuseumText: null,
    Descriptor: null,
    IsFragment: false,
    Status: 1,
    IsNew: true,
    LinkTypeId: null,
    TimeCr: '2019-01-25T12:17:44.000Z',
  },
  {
    Id: 4729,
    ResType: 'P',
    FileName: '2016/09/Sacrifice_Polyxena_BM_GR1897_7-27_2.jpg',
    ResLanguageId: null,
    ShowInGalery: true,
    Language: null,
    Name: 'Греки приносят в жертву дочь троянского царя Приама Поликсену (XIII—XII вв. до н. э.)',
    Description: null,
    AltAttribute: null,
    MetaData: '{"path":"2016/09/","mime-type":"image/jpeg","size":{"width":1024,"height":683},"content":{"m":"Sacrifice_Polyxena_BM_GR1897_7-27_2-768x512.jpg","s":"Sacrifice_Polyxena_BM_GR1897_7-27_2-360x240.jpg"},"icon":"Sacrifice_Polyxena_BM_GR1897_7-27_2-150x150.jpg"}',
    ArtifactText: null,
    AuthorText: null,
    MuseumText: null,
    Descriptor: null,
    IsFragment: false,
    Status: 1,
    IsNew: true,
    LinkTypeId: null,
    TimeCr: '2019-01-25T12:17:44.000Z',
  },
  {
    Id: 4730,
    ResType: 'P',
    FileName: '2016/09/ZHERTV-NIE.-Fragment.-San-Vitale.-Ravenna.-6-AD-big1.jpg',
    ResLanguageId: null,
    ShowInGalery: true,
    Language: null,
    Name: 'Мозаика Сан-Витале',
    Description: 'Равенна, VI век н.э.',
    AltAttribute: null,
    MetaData: '{"path":"2016/09/","mime-type":"image/jpeg","size":{"width":1446,"height":1024},"content":{"l":"ZHERTV-NIE.-Fragment.-San-Vitale.-Ravenna.-6-AD-big1-1366x967.jpg","m":"ZHERTV-NIE.-Fragment.-San-Vitale.-Ravenna.-6-AD-big1-768x544.jpg","s":"ZHERTV-NIE.-Fragment.-San-Vitale.-Ravenna.-6-AD-big1-360x255.jpg"},"icon":"ZHERTV-NIE.-Fragment.-San-Vitale.-Ravenna.-6-AD-big1-150x150.jpg"}',
    ArtifactText: null,
    AuthorText: null,
    MuseumText: null,
    Descriptor: null,
    IsFragment: false,
    Status: 1,
    IsNew: true,
    LinkTypeId: null,
    TimeCr: '2019-01-25T12:17:44.000Z',
  },
  {
    Id: 4731,
    ResType: 'P',
    FileName: '2016/09/ZHERTV-NIE.-Fragment.-San-Vitale.-Ravenna.-6-AD-detail_1.jpg',
    ResLanguageId: null,
    ShowInGalery: true,
    Language: null,
    Name: 'Мозаика Сан-Витале',
    Description: 'Равенна, VI век н.э. Деталь',
    AltAttribute: null,
    MetaData: '{"path":"2016/09/","mime-type":"image/jpeg","size":{"width":1005,"height":1024},"content":{"m":"ZHERTV-NIE.-Fragment.-San-Vitale.-Ravenna.-6-AD-detail_1-768x783.jpg","s":"ZHERTV-NIE.-Fragment.-San-Vitale.-Ravenna.-6-AD-detail_1-360x367.jpg"},"icon":"ZHERTV-NIE.-Fragment.-San-Vitale.-Ravenna.-6-AD-detail_1-150x150.jpg"}',
    ArtifactText: null,
    AuthorText: null,
    MuseumText: null,
    Descriptor: null,
    IsFragment: false,
    Status: 1,
    IsNew: true,
    LinkTypeId: null,
    TimeCr: '2019-01-25T12:17:44.000Z',
  },
  {
    Id: 4732,
    ResType: 'P',
    FileName: '2016/09/Beit_alfa_panorama2.jpg',
    ResLanguageId: null,
    ShowInGalery: true,
    Language: null,
    Name: 'Панорама напольной мозаики синагоги Бейт-Альфа, VI в.',
    Description: null,
    AltAttribute: null,
    MetaData: '{"path":"2016/09/","mime-type":"image/jpeg","size":{"width":1920,"height":533},"content":{"l":"Beit_alfa_panorama2-1366x379.jpg","m":"Beit_alfa_panorama2-768x213.jpg","s":"Beit_alfa_panorama2-360x100.jpg"},"icon":"Beit_alfa_panorama2-150x150.jpg"}',
    ArtifactText: null,
    AuthorText: null,
    MuseumText: null,
    Descriptor: null,
    IsFragment: false,
    Status: 1,
    IsNew: true,
    LinkTypeId: null,
    TimeCr: '2019-01-25T12:17:44.000Z',
  },
  {
    Id: 4733,
    ResType: 'P',
    FileName: '2016/09/ZHertv-nie.-Napolnaya-moz.-v-sin.-Bejt-Alfa-6-AD.-Marian-i-Hanan.jpg',
    ResLanguageId: null,
    ShowInGalery: true,
    Language: null,
    Name: 'Напольная мозаика в синагоге Бейт-Альфа, VI в. н.э.',
    Description: 'Художники-мозаичисты – Мариан и его сын Ханина',
    AltAttribute: null,
    MetaData: '{"path":"2016/09/","mime-type":"image/jpeg","size":{"width":708,"height":1067},"content":{"s":"ZHertv-nie.-Napolnaya-moz.-v-sin.-Bejt-Alfa-6-AD.-Marian-i-Hanan-360x543.jpg"},"icon":"ZHertv-nie.-Napolnaya-moz.-v-sin.-Bejt-Alfa-6-AD.-Marian-i-Hanan-150x150.jpg"}',
    ArtifactText: null,
    AuthorText: null,
    MuseumText: null,
    Descriptor: null,
    IsFragment: false,
    Status: 1,
    IsNew: true,
    LinkTypeId: null,
    TimeCr: '2019-01-25T12:17:44.000Z',
  },
  {
    Id: 4734,
    ResType: 'P',
    FileName: '2016/09/ZHertv-nie.-Napolnaya-moz.-v-sin.-Bejt-Alfa-6-AD.-Marian-i-Hanan-middle.jpg',
    ResLanguageId: null,
    ShowInGalery: true,
    Language: null,
    Name: 'Жертвоприношение Авраама',
    Description: 'Напольная мозаика в синагоге Бейт-Альфа. Деталь.',
    AltAttribute: null,
    MetaData: '{"path":"2016/09/","mime-type":"image/jpeg","size":{"width":812,"height":478},"content":{"m":"ZHertv-nie.-Napolnaya-moz.-v-sin.-Bejt-Alfa-6-AD.-Marian-i-Hanan-middle-768x452.jpg","s":"ZHertv-nie.-Napolnaya-moz.-v-sin.-Bejt-Alfa-6-AD.-Marian-i-Hanan-middle-360x212.jpg"},"icon":"ZHertv-nie.-Napolnaya-moz.-v-sin.-Bejt-Alfa-6-AD.-Marian-i-Hanan-middle-150x150.jpg"}',
    ArtifactText: null,
    AuthorText: null,
    MuseumText: null,
    Descriptor: null,
    IsFragment: false,
    Status: 1,
    IsNew: true,
    LinkTypeId: null,
    TimeCr: '2019-01-25T12:17:44.000Z',
  },
  {
    Id: 4735,
    ResType: 'P',
    FileName: '2016/09/MonrealeCathedral.jpg',
    ResLanguageId: null,
    ShowInGalery: true,
    Language: null,
    Name: 'Собор Монреале',
    Description: 'Сицилия, XII в.',
    AltAttribute: null,
    MetaData: '{"path":"2016/09/","mime-type":"image/jpeg","size":{"width":1024,"height":709},"content":{"m":"MonrealeCathedral-768x532.jpg","s":"MonrealeCathedral-360x249.jpg"},"icon":"MonrealeCathedral-150x150.jpg"}',
    ArtifactText: null,
    AuthorText: null,
    MuseumText: null,
    Descriptor: null,
    IsFragment: false,
    Status: 1,
    IsNew: true,
    LinkTypeId: null,
    TimeCr: '2019-01-25T12:17:44.000Z',
  },
  {
    Id: 4736,
    ResType: 'P',
    FileName: '2016/09/Abraham_offer_his_son_as_sacrificemiddle.-Monreale.-12-v.jpg',
    ResLanguageId: null,
    ShowInGalery: true,
    Language: null,
    Name: 'Жертвоприношение Авраама',
    Description: 'Мозаика. Собор Монреале, Сицилия',
    AltAttribute: null,
    MetaData: '{"path":"2016/09/","mime-type":"image/jpeg","size":{"width":703,"height":800},"content":{"s":"Abraham_offer_his_son_as_sacrificemiddle.-Monreale.-12-v-360x410.jpg"},"icon":"Abraham_offer_his_son_as_sacrificemiddle.-Monreale.-12-v-150x150.jpg"}',
    ArtifactText: null,
    AuthorText: null,
    MuseumText: null,
    Descriptor: null,
    IsFragment: false,
    Status: 1,
    IsNew: true,
    LinkTypeId: null,
    TimeCr: '2019-01-25T12:17:44.000Z',
  },
  {
    Id: 4737,
    ResType: 'P',
    FileName: '2016/09/Battistero-di-San-Giovanni.jpg',
    ResLanguageId: null,
    ShowInGalery: true,
    Language: null,
    Name: 'Флорентийский баптистерий (XI – XII вв.)',
    Description: null,
    AltAttribute: null,
    MetaData: '{"path":"2016/09/","mime-type":"image/jpeg","size":{"width":1024,"height":1024},"content":{"m":"Battistero-di-San-Giovanni-768x768.jpg","s":"Battistero-di-San-Giovanni-360x360.jpg"},"icon":"Battistero-di-San-Giovanni-150x150.jpg"}',
    ArtifactText: null,
    AuthorText: null,
    MuseumText: null,
    Descriptor: null,
    IsFragment: false,
    Status: 1,
    IsNew: true,
    LinkTypeId: null,
    TimeCr: '2019-01-25T12:17:44.000Z',
  },
  {
    Id: 4738,
    ResType: 'P',
    FileName: '2016/09/Giberti.-1401-Florentsiya.-Dveri-bapt-riya-big0.jpg',
    ResLanguageId: null,
    ShowInGalery: true,
    Language: null,
    Name: 'Восточные «Райские врата» флорентийского баптистерия (1401)',
    Description: 'Художник – Лоренцо Гиберти (1378 – 1455)',
    AltAttribute: null,
    MetaData: '{"path":"2016/09/","mime-type":"image/jpeg","size":{"width":683,"height":1024},"content":{"s":"Giberti.-1401-Florentsiya.-Dveri-bapt-riya-big0-360x540.jpg"},"icon":"Giberti.-1401-Florentsiya.-Dveri-bapt-riya-big0-150x150.jpg"}',
    ArtifactText: null,
    AuthorText: null,
    MuseumText: null,
    Descriptor: null,
    IsFragment: false,
    Status: 1,
    IsNew: true,
    LinkTypeId: null,
    TimeCr: '2019-01-25T12:17:44.000Z',
  },
  {
    Id: 4739,
    ResType: 'P',
    FileName: '2016/09/Giberti.-1401-Florentsiya.-Dveri-bapt-riya-big1.jpg',
    ResLanguageId: null,
    ShowInGalery: true,
    Language: null,
    Name: 'Восточные «Райские врата» флорентийского баптистерия (1401), деталь.',
    Description: null,
    AltAttribute: null,
    MetaData: '{"path":"2016/09/","mime-type":"image/jpeg","size":{"width":930,"height":1024},"content":{"m":"Giberti.-1401-Florentsiya.-Dveri-bapt-riya-big1-768x846.jpg","s":"Giberti.-1401-Florentsiya.-Dveri-bapt-riya-big1-360x396.jpg"},"icon":"Giberti.-1401-Florentsiya.-Dveri-bapt-riya-big1-150x150.jpg"}',
    ArtifactText: null,
    AuthorText: null,
    MuseumText: null,
    Descriptor: null,
    IsFragment: false,
    Status: 1,
    IsNew: true,
    LinkTypeId: null,
    TimeCr: '2019-01-25T12:17:44.000Z',
  },
  {
    Id: 4740,
    ResType: 'P',
    FileName: '2016/09/Karavadzho-ZHertvoprinosh-Isaaka-1602-Uffitsi-big.jpg',
    ResLanguageId: null,
    ShowInGalery: true,
    Language: null,
    Name: 'Жертвоприношение Исаака (1602)',
    Description: 'Художник – Микеланджело Меризи да Караваджо (итал. Michelangelo Merisi da Caravaggio; 1571 — 1610). Уффици.',
    AltAttribute: null,
    MetaData: '{"path":"2016/09/","mime-type":"image/jpeg","size":{"width":1329,"height":1024},"content":{"m":"Karavadzho-ZHertvoprinosh-Isaaka-1602-Uffitsi-big-768x592.jpg","s":"Karavadzho-ZHertvoprinosh-Isaaka-1602-Uffitsi-big-360x277.jpg"},"icon":"Karavadzho-ZHertvoprinosh-Isaaka-1602-Uffitsi-big-150x150.jpg"}',
    ArtifactText: null,
    AuthorText: null,
    MuseumText: null,
    Descriptor: null,
    IsFragment: false,
    Status: 1,
    IsNew: true,
    LinkTypeId: null,
    TimeCr: '2019-01-25T12:17:44.000Z',
  },
  {
    Id: 4741,
    ResType: 'P',
    FileName: '2016/09/Karavadzho-ZHertvoprinosh-Isaaka-1602-Uffitsi-detail-1.jpg',
    ResLanguageId: null,
    ShowInGalery: true,
    Language: null,
    Name: '',
    Description: null,
    AltAttribute: null,
    MetaData: '{"path":"2016/09/","mime-type":"image/jpeg","size":{"width":1920,"height":1080},"content":{"l":"Karavadzho-ZHertvoprinosh-Isaaka-1602-Uffitsi-detail-1-1366x768.jpg","m":"Karavadzho-ZHertvoprinosh-Isaaka-1602-Uffitsi-detail-1-768x432.jpg","s":"Karavadzho-ZHertvoprinosh-Isaaka-1602-Uffitsi-detail-1-360x203.jpg"},"icon":"Karavadzho-ZHertvoprinosh-Isaaka-1602-Uffitsi-detail-1-150x150.jpg"}',
    ArtifactText: null,
    AuthorText: null,
    MuseumText: null,
    Descriptor: null,
    IsFragment: false,
    Status: 1,
    IsNew: true,
    LinkTypeId: null,
    TimeCr: '2019-01-25T12:17:44.000Z',
  },
  {
    Id: 4742,
    ResType: 'P',
    FileName: '2016/09/Karavadzho-ZHertvoprinosh-Isaaka-1602-Uffitsi-detail-2.jpg',
    ResLanguageId: null,
    ShowInGalery: true,
    Language: null,
    Name: '',
    Description: null,
    AltAttribute: null,
    MetaData: '{"path":"2016/09/","mime-type":"image/jpeg","size":{"width":1920,"height":1080},"content":{"l":"Karavadzho-ZHertvoprinosh-Isaaka-1602-Uffitsi-detail-2-1366x768.jpg","m":"Karavadzho-ZHertvoprinosh-Isaaka-1602-Uffitsi-detail-2-768x432.jpg","s":"Karavadzho-ZHertvoprinosh-Isaaka-1602-Uffitsi-detail-2-360x203.jpg"},"icon":"Karavadzho-ZHertvoprinosh-Isaaka-1602-Uffitsi-detail-2-150x150.jpg"}',
    ArtifactText: null,
    AuthorText: null,
    MuseumText: null,
    Descriptor: null,
    IsFragment: false,
    Status: 1,
    IsNew: true,
    LinkTypeId: null,
    TimeCr: '2019-01-25T12:17:44.000Z',
  },
  {
    Id: 4743,
    ResType: 'P',
    FileName: '2016/09/Rembrandt_-_Abrahams_sacrifice_detail.jpg',
    ResLanguageId: null,
    ShowInGalery: true,
    Language: null,
    Name: '',
    Description: null,
    AltAttribute: null,
    MetaData: '{"path":"2016/09/","mime-type":"image/jpeg","size":{"width":864,"height":1080},"content":{"m":"Rembrandt_-_Abrahams_sacrifice_detail-768x960.jpg","s":"Rembrandt_-_Abrahams_sacrifice_detail-360x450.jpg"},"icon":"Rembrandt_-_Abrahams_sacrifice_detail-150x150.jpg"}',
    ArtifactText: null,
    AuthorText: null,
    MuseumText: null,
    Descriptor: null,
    IsFragment: false,
    Status: 1,
    IsNew: true,
    LinkTypeId: null,
    TimeCr: '2019-01-25T12:17:44.000Z',
  },
  {
    Id: 4744,
    ResType: 'P',
    FileName: '2016/09/Rembrandt_-_Abrahams_sacrifice_detail-hand.jpg',
    ResLanguageId: null,
    ShowInGalery: true,
    Language: null,
    Name: '',
    Description: null,
    AltAttribute: null,
    MetaData: '{"path":"2016/09/","mime-type":"image/jpeg","size":{"width":1503,"height":1074},"content":{"l":"Rembrandt_-_Abrahams_sacrifice_detail-hand-1366x976.jpg","m":"Rembrandt_-_Abrahams_sacrifice_detail-hand-768x549.jpg","s":"Rembrandt_-_Abrahams_sacrifice_detail-hand-360x257.jpg"},"icon":"Rembrandt_-_Abrahams_sacrifice_detail-hand-150x150.jpg"}',
    ArtifactText: null,
    AuthorText: null,
    MuseumText: null,
    Descriptor: null,
    IsFragment: false,
    Status: 1,
    IsNew: true,
    LinkTypeId: null,
    TimeCr: '2019-01-25T12:17:44.000Z',
  },
  {
    Id: 4745,
    ResType: 'P',
    FileName: '2016/09/Rembrandt_-_Abrahams_sacrifice_-_Google_Art_Projectdetail-1.jpg',
    ResLanguageId: null,
    ShowInGalery: true,
    Language: null,
    Name: '',
    Description: null,
    AltAttribute: null,
    MetaData: '{"path":"2016/09/","mime-type":"image/jpeg","size":{"width":1607,"height":1072},"content":{"l":"Rembrandt_-_Abrahams_sacrifice_-_Google_Art_Projectdetail-1-1366x911.jpg","m":"Rembrandt_-_Abrahams_sacrifice_-_Google_Art_Projectdetail-1-768x512.jpg","s":"Rembrandt_-_Abrahams_sacrifice_-_Google_Art_Projectdetail-1-360x240.jpg"},"icon":"Rembrandt_-_Abrahams_sacrifice_-_Google_Art_Projectdetail-1-150x150.jpg"}',
    ArtifactText: null,
    AuthorText: null,
    MuseumText: null,
    Descriptor: null,
    IsFragment: false,
    Status: 1,
    IsNew: true,
    LinkTypeId: null,
    TimeCr: '2019-01-25T12:17:44.000Z',
  },
  {
    Id: 4746,
    ResType: 'P',
    FileName: '2016/09/Rembrandt_-_Abrahams_sacrifice_-_Google_Art_Projectdetail-2.jpg',
    ResLanguageId: null,
    ShowInGalery: true,
    Language: null,
    Name: '',
    Description: null,
    AltAttribute: null,
    MetaData: '{"path":"2016/09/","mime-type":"image/jpeg","size":{"width":1225,"height":1064},"content":{"m":"Rembrandt_-_Abrahams_sacrifice_-_Google_Art_Projectdetail-2-768x667.jpg","s":"Rembrandt_-_Abrahams_sacrifice_-_Google_Art_Projectdetail-2-360x313.jpg"},"icon":"Rembrandt_-_Abrahams_sacrifice_-_Google_Art_Projectdetail-2-150x150.jpg"}',
    ArtifactText: null,
    AuthorText: null,
    MuseumText: null,
    Descriptor: null,
    IsFragment: false,
    Status: 1,
    IsNew: true,
    LinkTypeId: null,
    TimeCr: '2019-01-25T12:17:44.000Z',
  },
  {
    Id: 4747,
    ResType: 'P',
    FileName: '2016/09/Rembrandt_-_Abrahams_sacrifice_-_Google_Art_Projectdetail-3.jpg',
    ResLanguageId: null,
    ShowInGalery: true,
    Language: null,
    Name: '',
    Description: null,
    AltAttribute: '',
    MetaData: '{"path":"2016/09/","mime-type":"image/jpeg","size":{"width":1799,"height":1080},"content":{"l":"Rembrandt_-_Abrahams_sacrifice_-_Google_Art_Projectdetail-3-1366x820.jpg","m":"Rembrandt_-_Abrahams_sacrifice_-_Google_Art_Projectdetail-3-768x461.jpg","s":"Rembrandt_-_Abrahams_sacrifice_-_Google_Art_Projectdetail-3-360x216.jpg"},"icon":"Rembrandt_-_Abrahams_sacrifice_-_Google_Art_Projectdetail-3-150x150.jpg"}',
    ArtifactText: null,
    AuthorText: null,
    MuseumText: null,
    Descriptor: null,
    IsFragment: false,
    Status: 1,
    IsNew: true,
    LinkTypeId: null,
    TimeCr: '2019-01-25T12:17:44.000Z',
  },
  {
    Id: 4748,
    ResType: 'P',
    FileName: '2016/09/Rembrandt_-_Abrahams_sacrifice_-_Google_Art_Projectdetail-4.jpg',
    ResLanguageId: null,
    ShowInGalery: true,
    Language: null,
    Name: '',
    Description: null,
    AltAttribute: 'rembrandt_-_abrahams_sacrifice_-_google_art_project-detail-4',
    MetaData: '{"path":"2016/09/","mime-type":"image/jpeg","size":{"width":808,"height":1077},"content":{"m":"Rembrandt_-_Abrahams_sacrifice_-_Google_Art_Projectdetail-4-768x1024.jpg","s":"Rembrandt_-_Abrahams_sacrifice_-_Google_Art_Projectdetail-4-360x480.jpg"},"icon":"Rembrandt_-_Abrahams_sacrifice_-_Google_Art_Projectdetail-4-150x150.jpg"}',
    ArtifactText: null,
    AuthorText: null,
    MuseumText: null,
    Descriptor: null,
    IsFragment: false,
    Status: 1,
    IsNew: true,
    LinkTypeId: null,
    TimeCr: '2019-01-25T12:17:44.000Z',
  },
  {
    Id: 4749,
    ResType: 'P',
    FileName: '2016/09/Rembrandt-Titus.1641-68.-Wallace-Collection.-London.-1657.jpg',
    ResLanguageId: null,
    ShowInGalery: true,
    Language: null,
    Name: 'Потрет Титуса (1657)',
    Description: 'Художник – Рембрандт ван Рейн (нидерл. Rembrandt Harmenszoon van Rijn; 1606—1669)',
    AltAttribute: null,
    MetaData: '{"path":"2016/09/","mime-type":"image/jpeg","size":{"width":858,"height":1024},"content":{"m":"Rembrandt-Titus.1641-68.-Wallace-Collection.-London.-1657-768x917.jpg","s":"Rembrandt-Titus.1641-68.-Wallace-Collection.-London.-1657-360x430.jpg"},"icon":"Rembrandt-Titus.1641-68.-Wallace-Collection.-London.-1657-150x150.jpg"}',
    ArtifactText: null,
    AuthorText: null,
    MuseumText: null,
    Descriptor: null,
    IsFragment: false,
    Status: 1,
    IsNew: true,
    LinkTypeId: null,
    TimeCr: '2019-01-25T12:17:44.000Z',
  },
  {
    Id: 4750,
    ResType: 'P',
    FileName: '2016/09/Rembrandt-Titus.-Titus-van-Rejn.-1641-68-Reading-KHM-1656.jpg',
    ResLanguageId: null,
    ShowInGalery: true,
    Language: null,
    Name: 'Читающий Титус (1656)',
    Description: 'Художник – Рембрандт ван Рейн (нидерл. Rembrandt Harmenszoon van Rijn; 1606—1669)',
    AltAttribute: null,
    MetaData: '{"path":"2016/09/","mime-type":"image/jpeg","size":{"width":945,"height":1024},"content":{"m":"Rembrandt-Titus.-Titus-van-Rejn.-1641-68-Reading-KHM-1656-768x832.jpg","s":"Rembrandt-Titus.-Titus-van-Rejn.-1641-68-Reading-KHM-1656-360x390.jpg"},"icon":"Rembrandt-Titus.-Titus-van-Rejn.-1641-68-Reading-KHM-1656-150x150.jpg"}',
    ArtifactText: null,
    AuthorText: null,
    MuseumText: null,
    Descriptor: null,
    IsFragment: false,
    Status: 1,
    IsNew: true,
    LinkTypeId: null,
    TimeCr: '2019-01-25T12:17:44.000Z',
  },
  {
    Id: 4751,
    ResType: 'P',
    FileName: '2016/09/Rembrandt-St.-Matthew-and-The-Angel.-Louvre.-1661-big.jpg',
    ResLanguageId: null,
    ShowInGalery: true,
    Language: null,
    Name: 'Святой Матфей и ангел (1661)',
    Description: 'Художник – Рембрандт ван Рейн (нидерл. Rembrandt Harmenszoon van Rijn; 1606—1669)',
    AltAttribute: null,
    MetaData: '{"path":"2016/09/","mime-type":"image/jpeg","size":{"width":826,"height":1024},"content":{"m":"Rembrandt-St.-Matthew-and-The-Angel.-Louvre.-1661-big-768x952.jpg","s":"Rembrandt-St.-Matthew-and-The-Angel.-Louvre.-1661-big-360x446.jpg"},"icon":"Rembrandt-St.-Matthew-and-The-Angel.-Louvre.-1661-big-150x150.jpg"}',
    ArtifactText: null,
    AuthorText: null,
    MuseumText: null,
    Descriptor: null,
    IsFragment: false,
    Status: 1,
    IsNew: true,
    LinkTypeId: null,
    TimeCr: '2019-01-25T12:17:44.000Z',
  },
  {
    Id: 4752,
    ResType: 'P',
    FileName: '2016/09/Rembrandt_Portrait_of_Titus_van_Rijn_1668big.jpg',
    ResLanguageId: null,
    ShowInGalery: true,
    Language: null,
    Name: 'Портрет Титуса (1668)',
    Description: 'Художник – Рембрандт ван Рейн (нидерл. Rembrandt Harmenszoon van Rijn; 1606—1669)',
    AltAttribute: null,
    MetaData: '{"path":"2016/09/","mime-type":"image/jpeg","size":{"width":824,"height":1055},"content":{"m":"Rembrandt_Portrait_of_Titus_van_Rijn_1668big-768x983.jpg","s":"Rembrandt_Portrait_of_Titus_van_Rijn_1668big-360x461.jpg"},"icon":"Rembrandt_Portrait_of_Titus_van_Rijn_1668big-150x150.jpg"}',
    ArtifactText: null,
    AuthorText: null,
    MuseumText: null,
    Descriptor: null,
    IsFragment: false,
    Status: 1,
    IsNew: true,
    LinkTypeId: null,
    TimeCr: '2019-01-25T12:17:44.000Z',
  },
];

export default lessonImages;
