export const SWITCH_SIZE_TO = 'SWITCH_SIZE_TO';
export const SWITCH_TO_SMALL_PLAYER = 'SWITCH_TO_SMALL_PLAYER';
export const DUMMY_SWITCH_TO_SMALL_PLAYER = 'DUMMY_SWITCH_TO_SMALL_PLAYER';
export const SWITCH_TO_FULL_PLAYER = 'SWITCH_TO_FULL_PLAYER';
export const CLEAR_FULL_VIEWPORT = 'CLEAR_FULL_VIEWPORT';

export const HIDE_LESSON_MENU = 'HIDE_LESSON_MENU';
export const SHOW_LESSON_MENU = 'SHOW_LESSON_MENU';