export const SWITCH_SIZE_TO = 'SWITCH_SIZE_TO';
export const SWITCH_TO_SMALL_PLAYER = 'SWITCH_TO_SMALL_PLAYER';
export const SWITCH_TO_FULL_PLAYER = 'SWITCH_TO_FULL_PLAYER';

export const HIDE_LESSON_MENU = 'HIDE_LESSON_MENU';
export const SHOW_LESSON_MENU = 'SHOW_LESSON_MENU';