export const GET_COURSES_REQUEST = 'GET_COURSES_REQUEST';
export const GET_COURSES_SUCCESS = 'GET_COURSES_SUCCESS';
export const GET_COURSES_FAIL = 'GET_COURSES_FAIL';

export const GET_SINGLE_COURSE_REQUEST = 'GET_SINGLE_COURSE_REQUEST';
export const GET_SINGLE_COURSE_SUCCESS = 'GET_SINGLE_COURSE_SUCCESS';
export const GET_SINGLE_COURSE_FAIL = 'GET_SINGLE_COURSE_FAIL';

export const SET_COURSE_NOT_FOUND = 'SET_COURSE_NOT_FOUND';
