export const CLEAR_FILTERS = 'CLEAR_FILTERS';
export const LOAD_FILTER_VALUES = 'LOAD_FILTER_VALUES';
export const SWITCH_FILTERS = 'SWITCH_FILTERS';


export const FILTER_COURSE_TYPE = {
    THEORY: 1,
    PRACTICE: 2,
}