export const GET_LESSON_REQUEST = 'GET_LESSON_REQUEST';
export const GET_LESSON_SUCCESS = 'GET_LESSON_SUCCESS';
export const GET_LESSON_FAIL = 'GET_LESSON_FAIL';

export const GET_LESSONS_ALL_REQUEST = 'GET_LESSONS_ALL_REQUEST';
export const GET_LESSONS_ALL_SUCCESS = 'GET_LESSONS_ALL_SUCCESS';
export const GET_LESSONS_ALL_FAIL = 'GET_LESSONS_ALL_FAIL';