export const SHOW_SEARCH_FORM = 'SHOW_SEARCH_FORM';
export const HIDE_SEARCH_FORM = 'HIDE_SEARCH_FORM';
export const SHOW_FILTERS_FORM = 'SHOW_FILTERS_FORM';
export const HIDE_FILTER_FORM = 'HIDE_FILTER_FORM';
export const SHOW_MENU = 'SHOW_MENU';
export const HIDE_MENU = 'HIDE_MENU';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';