export const PLAYER_PLAYED = 'PLAYER_PLAYED';
export const PLAYER_PAUSED = 'PLAYER_PAUSED';
export const PLAYER_STOPPED = 'PLAYER_STOPPED';

export const PLAYER_SET_CURRENT_TIME = 'PLAYER_SET_CURRENT_TIME';
export const PLAYER_SET_TITLE = 'PLAYER_SET_TITLE';
// export const PLAYER_SETTOP = 'PLAYER_STOP';

export const PLAYER_START_PLAY = 'PLAYER_START_PLAY';
export const PLAYER_START_PAUSE = 'PLAYER_START_PAUSE';
export const PLAYER_START_STOP = 'PLAYER_START_STOP';
export const PLAYER_START_SET_CURRENT_TIME = 'PLAYER_START_SET_CURRENT_TIME';

