export const PLAYER_SET_SMALL_VIEWPORT = 'PLAYER_SET_SMALL_VIEWPORT';
export const PLAYER_SET_FULL_VIEWPORT = 'PLAYER_SET_FULL_VIEWPORT';
export const PLAYER_CLEAR_FULL_VIEWPORT = 'PLAYER_CLEAR_FULL_VIEWPORT';

export const PLAYER_START_PLAY_LESSON = 'PLAYER_START_PLAY_LESSON';

export const PLAYER_PLAYED = 'PLAYER_PLAYED';
export const PLAYER_PAUSED = 'PLAYER_PAUSED';
export const PLAYER_STOPPED = 'PLAYER_STOPPED';
export const PLAYER_ENDED = 'PLAYER_ENDED';

export const PLAYER_SET_CURRENT_TIME = 'PLAYER_SET_CURRENT_TIME';
export const PLAYER_SET_BUFFERED_TIME = 'PLAYER_SET_BUFFERED_TIME';
export const PLAYER_SET_TITLE = 'PLAYER_SET_TITLE';
export const PLAYER_SET_MUTE_STATE = 'PLAYER_SET_MUTE_STATE';
export const PLAYER_SET_VOLUME = 'PLAYER_SET_VOLUME';
export const PLAYER_SET_CONTENT_ARRAY = 'PLAYER_SET_CONTENT_ARRAY';
export const PLAYER_SET_CURRENT_CONTENT = 'PLAYER_SET_CURRENT_CONTENT';
export const PLAYER_SET_RATE = 'PLAYER_SET_RATE';

export const PLAYER_START_PLAY = 'PLAYER_START_PLAY';
export const PLAYER_START_REPLAY = 'PLAYER_START_REPLAY';
export const PLAYER_START_PAUSE = 'PLAYER_START_PAUSE';
export const PLAYER_START_STOP = 'PLAYER_START_STOP';
export const PLAYER_START_SET_CURRENT_TIME = 'PLAYER_START_SET_CURRENT_TIME';
export const PLAYER_TOGGLE_MUTE = 'PLAYER_TOGGLE_MUTE';
export const PLAYER_START_SET_VOLUME = 'PLAYER_START_SET_VOLUME';
export const PLAYER_START_SET_RATE = 'PLAYER_START_SET_RATE';

export const PLAYER_PREINIT_AUDIOS = 'PLAYER_PREINIT_AUDIOS';
export const PLAYER_CLEAR_AUDIOS = 'PLAYER_CLEAR_AUDIOS';
export const PLAYER_START_INIT = 'PLAYER_START_INIT';

