export const SIGN_UP_START = 'SIGN_UP_START';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAIL = 'SIGN_UP_FAIL';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';

export const SIGN_IN_START = 'SIGN_IN_START';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAIL = 'SIGN_IN_FAIL';

export const SHOW_SIGN_IN_FORM = 'SHOW_SIGN_IN_FORM';
export const CLOSE_SIGN_IN_FORM = 'CLOSE_SIGN_IN_FORM';

export const SWITCH_TO_SIGN_IN = 'SWITCH_TO_SIGN_IN';
export const SWITCH_TO_SIGN_UP = 'SWITCH_TO_SIGN_UP';

export const SET_SIGN_IN_CAPTCHA = 'SET_SIGN_IN_CAPTCHA';

export const AUTHORIZATION_STATE = {
    START_SIGN_IN : 'START_SIGN_IN',
    START_SIGN_UP : 'START_SIGN_UP',

}