export const SIGN_UP_START = 'SIGN_UP_START';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAIL = 'SIGN_UP_FAIL';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';

export const SIGN_IN_START = 'SIGN_IN_START';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAIL = 'SIGN_IN_FAIL';

export const SHOW_SIGN_IN_FORM = 'SHOW_SIGN_IN_FORM';
export const CLOSE_SIGN_IN_FORM = 'CLOSE_SIGN_IN_FORM';

export const SWITCH_TO_SIGN_IN = 'SWITCH_TO_SIGN_IN';
export const SWITCH_TO_SIGN_UP = 'SWITCH_TO_SIGN_UP';
export const SWITCH_TO_SIGN_UP_SUCCESS = 'SWITCH_TO_SIGN_UP_SUCCESS';

export const SET_SIGN_IN_CAPTCHA = 'SET_SIGN_IN_CAPTCHA';

export const ACTIVATION_START = 'ACTIVATION_START';
export const ACTIVATION_SUCCESS = 'ACTIVATION_SUCCESS';
export const ACTIVATION_FAIL = 'ACTIVATION_FAIL';

export const SWITCH_TO_RECOVERY_PASSWORD = 'SWITCH_TO_RECOVERY_PASSWORD';
export const SWITCH_TO_PASSWORD_CONFIRM = 'SWITCH_TO_PASSWORD_CONFIRM';
export const RECOVERY_START = 'RECOVERY_START';
export const RECOVERY_SUCCESS = 'RECOVERY_SUCCESS';
export const RECOVERY_FAIL = 'RECOVERY_FAIL';

export const LOGOUT_START = 'LOGOUT_START';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';

export const GET_ACTIVATION_USER_START = 'GET_ACTIVATION_USER_START';
export const GET_ACTIVATION_USER_SUCCESS = 'GET_ACTIVATION_USER_SUCCESS';
export const GET_ACTIVATION_USER_FAIL = 'GET_ACTIVATION_USER_FAIL';

export const RESEND_MESSAGE = 'RESEND_MESSAGE';

export const RECOVERY_PASSWORD_START = 'RECOVERY_PASSWORD_START';
export const RECOVERY_PASSWORD_SUCCESS = 'RECOVERY_PASSWORD_SUCCESS';
export const RECOVERY_PASSWORD_FAIL = 'RECOVERY_PASSWORD_FAIL';

export const SEND_NEW_PASSWORD_START = 'SEND_NEW_PASSWORD_START';
export const SEND_NEW_PASSWORD_SUCCESS = 'SEND_NEW_PASSWORD_SUCCESS';
export const SEND_NEW_PASSWORD_FAIL = 'SEND_NEW_PASSWORD_FAIL';


export const SWITCH_TO_RECOVERY_PASSWORD_SUCCESS = 'SWITCH_TO_RECOVERY_PASSWORD_SUCCESS';
export const SWITCH_TO_RECOVERY_PASSWORD_MESSAGE = 'SWITCH_TO_RECOVERY_PASSWORD_MESSAGE';

export const AUTHORIZATION_STATE = {
    NONE: 'NONE',
    START_SIGN_IN: 'START_SIGN_IN',
    START_SIGN_UP: 'START_SIGN_UP',
    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
    RECOVERY_PASSWORD: 'RECOVERY_PASSWORD',
    RECOVERY_PASSWORD_SUCCESS: 'RECOVERY_PASSWORD_SUCCESS',
    PASSWORD_CONFIRM: 'PASSWORD_CONFIRM',
    PASSWORD_CONFIRM_FINISHED: 'PASSWORD_CONFIRM_FINISHED',
}