import { StyleSheet, TextStyle, ViewStyle } from 'react-native';

type Styles = {
  wrapper: ViewStyle,
  header: ViewStyle,
  headerText: ViewStyle,
  details: ViewStyle,
  description: ViewStyle,
  button: ViewStyle,
  references: ViewStyle,
  title: TextStyle,
  date: TextStyle,
  referenceBox: ViewStyle,
  referenceItem: TextStyle,
  courseReference: ViewStyle,
  courseReferenceItem: TextStyle,
  lessonReferenceBox: ViewStyle,
  lessonReferenceHeader: TextStyle,
  lessonReferenceItem: TextStyle,
};

export default StyleSheet.create<Styles>({
  wrapper: {
    position: 'absolute',
    display: 'flex',
    flexDirection: 'column',
    borderRadius: 8,
    zIndex: 50,
    left: 21,
  },
  header: {
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    paddingLeft: 16,
    paddingRight: 8,
    paddingTop: 16,
    paddingBottom: 8,
    flex: 1,
    flexDirection: 'row',
  },
  headerText: {
    flex: 1,
    flexDirection: 'column',
  },
  details: {
    flexGrow: 1,
    backgroundColor: '#2F2F2F',
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 8,
    borderBottomLeftRadius: 8,
    borderBottomRightRadius: 8,
  },
  description: {
    color: '#FFFFFF',
    fontFamily: 'Fira Sans',
    fontSize: 12,
    lineHeight: 16.8,
    maxHeight: 84,
    // @ts-ignore
    overflow: 'auto',
  },
  title: {
    color: '#FFFFFF',
    fontFamily: 'Fira Sans',
    fontSize: 15,
    lineHeight: 19.5,
    fontWeight: 'bold',
  },
  references: {
    color: '#FFFFFF',
    fontFamily: 'Fira Sans',
    fontSize: 14,
    lineHeight: 17,
    fontWeight: 'bold',
    marginBottom: 6,
  },
  referenceBox: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: '#363636',
    borderRadius: 4,
    maxHeight: 32,
    marginBottom: 8
  },
  referenceItem: {
    color: '#FFFFFF',
    fontSize: 14,
    fontFamily: 'Fira Sans',
    fontWeight: '100',
    marginTop: 4,
    marginBottom: 4,
    marginRight: 8,
  },
  courseReference: {
    flex: 1,
    flexDirection: 'row',
    color: '#9d9d9d',
    fontFamily: 'Fira Sans',
    fontSize: 14,
    lineHeight: 17,
    marginTop: 4,
    marginBottom: 8,
  },
  courseReferenceItem: {
    color: '#9d9d9d',
    fontFamily: 'Fira Sans',
    fontSize: 14,
    lineHeight: 17,
  },
  lessonReferenceBox: {
    flex: 1,
    flexShrink: 1,
    flexDirection: 'row',
    backgroundColor: '#363636',
    marginTop: 6,
    marginBottom: 6,
    borderRadius: 4,
    maxHeight: 32,
    overflow: 'hidden',
  },
  lessonReferenceHeader:{
    color: '#adadad',
    flexDirection: 'row',
    fontFamily: 'Fira Sans',
    fontSize: 12,
    width: 30,
    paddingLeft: 4,
    paddingTop: 4
  },
  lessonReferenceItem: {
    fontFamily: 'Fira Sans',
    fontSize: 12,
    marginLeft: 8,
    marginTop: 4,
    marginBottom: 4,
    color: '#adadad',
    fontWeight: 'normal',
    textAlign: 'left'
  },

  date: {
    color: '#FFFFFF',
    fontFamily: 'Fira Sans',
    fontSize: 13,
    lineHeight: 15.6,
    marginTop: 1,
  },
  button: {
    marginLeft: 8,
    marginRight: 0,
  },
});
