export const SELECT_EPISODE_CONTENT = 'SELECT_EPISODE_CONTENT';
export const REMOVE_EPISODE_CONTENT = 'REMOVE_EPISODE_CONTENT';
export const MOVE_EPISODE_CONTENT_UP = 'MOVE_EPISODE_CONTENT_UP';
export const MOVE_EPISODE_CONTENT_DOWN = 'MOVE_EPISODE_CONTENT_DOWN';
export const ADD_EPISODE_CONTENT = 'ADD_EPISODE_CONTENT';