export const CREATE_RESOURCE = 'CREATE_RESOURCE';
export const EDIT_RESOURCE = 'EDIT_RESOURCE';
export const CLEAR_RESOURCE = 'CLEAR_RESOURCE';

export const SELECT_RESOURCE = 'SELECT_RESOURCE';
export const INSERT_RESOURCE = 'INSERT_RESOURCE';
export const UPDATE_RESOURCE = 'UPDATE_RESOURCE';
export const REMOVE_RESOURCE = 'REMOVE_RESOURCE';
export const MOVE_RESOURCE_UP = 'MOVE_RESOURCE_UP';
export const MOVE_RESOURCE_DOWN = 'MOVE_RESOURCE_DOWN';
