export const SELECT_COMMON_REFERENCE = 'SELECT_COMMON_REFERENCE';
export const INSERT_COMMON_REFERENCE = 'INSERT_COMMON_REFERENCE';
export const UPDATE_COMMON_REFERENCE = 'UPDATE_COMMON_REFERENCE';
export const REMOVE_COMMON_REFERENCE = 'REMOVE_COMMON_REFERENCE';
export const MOVE_COMMON_REFERENCE_UP = 'MOVE_COMMON_REFERENCE_UP';
export const MOVE_COMMON_REFERENCE_DOWN = 'MOVE_COMMON_REFERENCE_DOWN';