export const SELECT_RECOMMENDED_REFERENCE = 'SELECT_RECOMMENDED_REFERENCE';
export const INSERT_RECOMMENDED_REFERENCE = 'INSERT_RECOMMENDED_REFERENCE';
export const UPDATE_RECOMMENDED_REFERENCE = 'UPDATE_RECOMMENDED_REFERENCE';
export const REMOVE_RECOMMENDED_REFERENCE = 'REMOVE_RECOMMENDED_REFERENCE';
export const MOVE_RECOMMENDED_REFERENCE_UP = 'MOVE_RECOMMENDED_REFERENCE_UP';
export const MOVE_RECOMMENDED_REFERENCE_DOWN = 'MOVE_RECOMMENDED_REFERENCE_DOWN';