export const SELECT_MAIN_EPISODE = 'SELECT_MAIN_EPISODE';
export const REMOVE_MAIN_EPISODE = 'REMOVE_MAIN_EPISODE';
export const MOVE_MAIN_EPISODE_UP = 'MOVE_MAIN_EPISODE_UP';
export const MOVE_MAIN_EPISODE_DOWN = 'MOVE_MAIN_EPISODE_DOWN';