export const CREATE_NEW_LESSON = 'CREATE_NEW_LESSON';
export const GET_SINGLE_LESSON_REQUEST = 'GET_SINGLE_LESSON_REQUEST';
export const GET_SINGLE_LESSON_SUCCESS = 'GET_SINGLE_LESSON_SUCCESS';
export const GET_SINGLE_LESSON_FAIL = 'GET_SINGLE_LESSON_FAIL';
export const CHANGE_LESSON_DATA = 'CHANGE_LESSON_DATA';
export const CANCEL_CHANGE_LESSON_DATA = 'CANCEL_CHANGE_LESSON_DATA';

export const GET_LESSON_RESOURCES_REQUEST = 'GET_LESSON_RESOURCES_REQUEST';
export const GET_LESSON_RESOURCES_SUCCESS = 'GET_LESSON_RESOURCES_SUCCESS';
export const GET_LESSON_RESOURCES_FAIL = 'GET_LESSON_RESOURCES_FAIL';

export const SAVE_LESSON_SUCCESS = 'SAVE_LESSON_SUCCESS';
export const CLEAR_LESSON = 'CLEAR_LESSON';

export const SET_PARENT_LESSON = 'SET_PARENT_LESSON';
export const CLEAR_PARENT_LESSON = 'CLEAR_PARENT_LESSON';

export const SET_OG_IMAGE_RESOURCE_ID = 'SET_OG_IMAGE_RESOURCE_ID';
export const SET_TWITTER_IMAGE_RESOURCE_ID = 'SET_TWITTER_IMAGE_RESOURCE_ID';