module.exports = {
    "Elements": [{"Id": 1, "State": 1, "ElemId": 1, "TaskId": null, "SupervisorId": 2}, {
        "Id": 2,
        "State": 1,
        "ElemId": 2,
        "TaskId": null,
        "SupervisorId": null
    }],
    "Tasks": [{
        "Id": 1,
        "Name": "TEST1",
        "State": 1,
        "DueDate": "2021-02-23T21:00:00.000Z",
        "ExecutorId": 10169,
        "Description": "Аргументы locales и options поддерживаются ещё не всеми браузерами. Для проверки того, поддерживает ли их уже реализация, можно затребовать несуществующую метку языка и проверить, будет ли выброшено исключение RangeError:",
        "AlertId": null,
        "IsElementReady": 2,
        "WriteFieldSet": "set #1",
        "IsElemready": false
    }, {
        "Id": 2,
        "Name": "Task #2",
        "State": 1,
        "DueDate": "2021-02-22T21:00:00.000Z",
        "ExecutorId": 2,
        "Description": "Описание задачи №2\nДля проверки сохрания",
        "AlertId": null,
        "IsElementReady": 2,
        "WriteFieldSet": "set #1",
        "IsElemready": false
    }],
    "Deps": [],
    "Id": 1,
    "SysTypeId": 101,
    "Name": "Process #1",
    "State": 1,
    "StructId": 1,
    "SupervisorId": 2,
    "LessonId": 1,
    "DueDate": "2021-02-16T21:00:00.000Z",
    "AudioIniURL": "dfsadfsafs",
    "AudioIniComment": "Пример поля для редактирования",
    "InstrToAudioEdt": null,
    "AudioProcURL": null,
    "TranscriptURL": null,
    "PicDescriptionURL": null,
    "PicSrcURL": null,
    "PicAuthorURL": null,
    "PicFinalURL": null,
    "TechTransTiterURL": null,
    "TechTransEditURL": null,
    "RefsURL": null,
    "AudioFinalURL": null,
    "AudioNotes": null,
    "TechTransTimeURL": null,
    "TechTransMusicURL": null,
    "AllCompsFinalURL": null
}
