export const GET_AUTHORS_REQUEST = 'GET_AUTHORS_REQUEST';
export const GET_AUTHORS_SUCCESS = 'GET_AUTHORS_SUCCESS';
export const GET_AUTHORS_FAIL = 'GET_AUTHORS_FAIL';
export const SELECT_AUTHOR = 'SELECT_AUTHOR';
export const DELETE_AUTHOR_SUCCESS = 'DELETE_AUTHOR_SUCCESS';
export const SHOW_EDIT_AUTHOR_DLG = "SHOW_EDIT_AUTHOR_DLG";
export const HIDE_EDIT_AUTHOR_DLG = "HIDE_EDIT_AUTHOR_DLG";