export const CREATE_NEW_AUTHOR = 'CREATE_NEW_AUTHOR';
export const GET_AUTHOR_REQUEST = 'GET_AUTHOR_REQUEST';
export const GET_AUTHOR_SUCCESS = 'GET_AUTHOR_SUCCESS';
export const GET_AUTHOR_FAIL = 'GET_AUTHOR_FAIL';
export const CHANGE_AUTHOR_DATA = 'CHANGE_AUTHOR_DATA';
export const CANCEL_CHANGE_AUTHOR_DATA = 'CANCEL_CHANGE_AUTHOR_DATA';
export const SAVE_AUTHOR_DATA = 'SAVE_AUTHOR_DATA';
export const CLEAR_AUTHOR = 'CLEAR_AUTHOR';