export const GET_AUTHORS_LIST_REQUEST = 'GET_AUTHORS_LIST_REQUEST';
export const GET_AUTHORS_LIST_SUCCESS = 'GET_AUTHORS_LIST_SUCCESS';
export const GET_AUTHORS_LIST_FAIL = 'GET_AUTHORS_LIST_FAIL';
export const SELECT_AUTHOR = 'SELECT_AUTHOR';
export const DELETE_AUTHOR_SUCCESS = 'DELETE_AUTHOR_SUCCESS';
export const SHOW_EDIT_AUTHOR_DLG = "SHOW_EDIT_AUTHOR_DLG";
export const HIDE_EDIT_AUTHOR_DLG = "HIDE_EDIT_AUTHOR_DLG";