export const GET_AUTHORS_REQUEST = 'GET_AUTHORS_REQUEST';
export const GET_AUTHORS_SUCCESS = 'GET_AUTHORS_SUCCESS';
export const GET_AUTHORS_FAIL = 'GET_AUTHORS_FAIL';
export const SELECT_AUTHOR = 'SELECT_AUTHOR';