export const CREATE_NEW_CATEGORY = 'CREATE_NEW_CATEGORY';
export const GET_CATEGORY_REQUEST = 'GET_CATEGORY_REQUEST';
export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS';
export const GET_CATEGORY_FAIL = 'GET_CATEGORY_FAIL';
export const CHANGE_CATEGORY_DATA = 'CHANGE_CATEGORY_DATA';
export const CANCEL_CHANGE_CATEGORY_DATA = 'CANCEL_CHANGE_CATEGORY_DATA';
export const SAVE_CATEGORY_DATA = 'SAVE_CATEGORY_DATA';
export const CLEAR_CATEGORY = 'CLEAR_CATEGORY';