export const GET_CATEGORIES_REQUEST = 'GET_CATEGORIES_REQUEST';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAIL = 'GET_CATEGORIES_FAIL';
export const SELECT_CATEGORY = 'SELECT_CATEGORY';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const SHOW_EDIT_CATEGORY_DLG = "SHOW_EDIT_CATEGORY_DLG";
export const HIDE_EDIT_CATEGORY_DLG = "HIDE_EDIT_CATEGORY_DLG";