export const GET_COURSE_LESSONS_SUCCESS = 'GET_COURSE_LESSONS_SUCCESS';
// export const GET_COURSE_LESSONS_SUCCESS = 'GET_COURSE_LESSONS_SUCCESS';
export const MOVE_LESSON_UP = 'MOVE_LESSON_UP';
export const MOVE_LESSON_DOWN = 'MOVE_LESSON_DOWN';