/**
 * Created by levan.kiknadze on 12/11/2017.
 */

export const GET_EPISODES_REQUEST = 'GET_EPISODES_REQUEST'
export const GET_EPISODES_SUCCESS = 'GET_PHOTOS_SUCCESS'
export const GET_EPISODES_FAIL = 'GET_PHOTOS_FAIL'
export const SELECT_EPISODE = 'SELECT_EPISODE'
export const SHOW_DELETE_DLG = 'SHOW_DELETE_DLG'
export const DELETE_EPISODE_SUCCESS = 'DELETE_EPISODE_SUCCESS'
export const SHOW_ERROR_DIALOG = "SHOW_ERROR_DIALOG"
export const HIDE_ERROR_DIALOG = "HIDE_ERROR_DIALOG"
export const HIDE_DELETE_DLG = "HIDE_DELETE_DLG"
export const SHOW_EDIT_DLG = "SHOW_EDIT_DLG"
export const HIDE_EDIT_DLG = "HIDE_EDIT_DLG"
export const EDIT_MODE_EDIT = "edit"
export const EDIT_MODE_INSERT = "insert"
