export const GET_EPISODES_REQUEST = 'GET_EPISODES_REQUEST';
export const GET_EPISODES_SUCCESS = 'GET_PHOTOS_SUCCESS';
export const GET_EPISODES_FAIL = 'GET_PHOTOS_FAIL';
export const SELECT_EPISODE = 'SELECT_EPISODE';
export const DELETE_EPISODE_SUCCESS = 'DELETE_EPISODE_SUCCESS';
export const SHOW_EDIT_EPISODE_DLG = "SHOW_EDIT_DLG"
export const HIDE_EDIT_EPISODE_DLG = "HIDE_EDIT_DLG"
