export const SELECT_RESOURCE = 'SELECT_RESOURCE';
export const REMOVE_RESOURCE = 'REMOVE_RESOURCE';
export const MOVE_RESOURCE_UP = 'MOVE_RESOURCE_UP';
export const MOVE_RESOURCE_DOWN = 'MOVE_RESOURCE_DOWN';
export const ADD_RESOURCE = 'ADD_RESOURCE';