
export const SELECT_LESSON = 'SELECT_LESSON';
export const ADD_LESSON_REQUEST = 'ADD_LESSON_REQUEST';
export const ADD_LESSON_SUCCESS = 'ADD_LESSON_SUCCESS';
export const ADD_LESSON_FAIL = 'ADD_LESSON_FAIL';