// export const SHOW_EDIT_REFERENCE_DLG = "SHOW_EDIT_REFERENCE_DLG";
// export const HIDE_EDIT_REFERENCE_DLG = "HIDE_EDIT_REFERENCE_DLG";
export const CREATE_NEW_REFERENCE = 'CREATE_NEW_REFERENCE';
export const EDIT_REFERENCE = 'EDIT_REFERENCE';
export const CLEAR_REFERENCE = 'CLEAR_REFERENCE';
export const CHANGE_REFERENCE_DATA = 'CHANGE_REFERENCE_DATA';
export const CANCEL_CHANGE_REFERENCE_DATA = 'CANCEL_CHANGE_REFERENCE_DATA';