export const CREATE_RESOURCE = 'CREATE_RESOURCE';
export const EDIT_RESOURCE = 'EDIT_RESOURCE';
export const CLEAR_RESOURCE = 'CLEAR_RESOURCE';
export const CHANGE_REFERENCE_DATA = 'CHANGE_REFERENCE_DATA';
export const CANCEL_CHANGE_REFERENCE_DATA = 'CANCEL_CHANGE_REFERENCE_DATA';