export const CREATE_NEW_LESSON = 'CREATE_NEW_LESSON';
export const GET_SINGLE_LESSON_REQUEST = 'GET_SINGLE_LESSON_REQUEST';
export const GET_SINGLE_LESSON_SUCCESS = 'GET_SINGLE_LESSON_SUCCESS';
export const GET_SINGLE_LESSON_FAIL = 'GET_SINGLE_LESSON_FAIL';
// export const SHOW_ADD_EPISODE_DIALOG = 'SHOW_ADD_AUTHOR_DIALOG';
// export const HIDE_ADD_AUTHOR_DIALOG = 'HIDE_ADD_AUTHOR_DIALOG';
// export const ADD_AUTHOR = 'ADD_AUTHOR';
// export const REMOVE_AUTHOR = 'REMOVE_AUTHOR';
// export const SHOW_ADD_CATEGORY_DIALOG = 'SHOW_ADD_CATEGORY_DIALOG';
// export const ADD_CATEGORY = 'ADD_CATEGORY';
// export const REMOVE_CATEGORY = 'REMOVE_CATEGORY';
// export const HIDE_ADD_CATEGORY_DIALOG = 'HIDE_ADD_CATEGORY_DIALOG';
// export const ADD_AUTHOR_FAIL = 'ADD_AUTHOR_FAIL';
export const CHANGE_LESSON_DATA = 'CHANGE_LESSON_DATA';
export const CANCEL_CHANGE_LESSON_DATA = 'CANCEL_CHANGE_LESSON_DATA';
// export const ADD_LESSON = 'ADD_LESSON';
// export const REMOVE_LESSON = 'REMOVE_LESSON';

// export const ADD_MA = 'ADD_LESSON';
export const REMOVE_MAIN_EPISODE = 'REMOVE_MAIN_EPISODE';
export const MOVE_MAIN_EPISODE_UP = 'MOVE_MAIN_EPISODE_UP';
export const MOVE_MAIN_EPISODE_DOWN = 'MOVE_MAIN_EPISODE_DOWN';
export const REMOVE_SUPP_EPISODE = 'REMOVE_SUPP_EPISODE';
export const MOVE_SUPP_EPISODE_UP = 'MOVE_SUPP_EPISODE_UP';
export const MOVE_SUPP_EPISODE_DOWN = 'MOVE_SUPP_EPISODE_DOWN';

export const INSERT_RECOMMENDED_REFERENCE = 'INSERT_RECOMMENDED_REFERENCE';
export const UPDATE_RECOMMENDED_REFERENCE = 'UPDATE_RECOMMENDED_REFERENCE';
export const REMOVE_RECOMMENDED_REFERENCE = 'REMOVE_RECOMMENDED_REFERENCE';
export const MOVE_RECOMMENDED_REFERENCE_UP = 'MOVE_RECOMMENDED_REFERENCE_UP';
export const MOVE_RECOMMENDED_REFERENCE_DOWN = 'MOVE_RECOMMENDED_REFERENCE_DOWN';

export const INSERT_COMMON_REFERENCE = 'INSERT_COMMON_REFERENCE';
export const UPDATE_COMMON_REFERENCE = 'UPDATE_COMMON_REFERENCE';
export const REMOVE_COMMON_REFERENCE = 'REMOVE_COMMON_REFERENCE';
export const MOVE_COMMON_REFERENCE_UP = 'MOVE_COMMON_REFERENCE_UP';
export const MOVE_COMMON_REFERENCE_DOWN = 'MOVE_COMMON_REFERENCE_DOWN';