export const CREATE_NEW_EPISODE = 'CREATE_NEW_EPISODE';
export const GET_SINGLE_EPISODE_REQUEST = 'GET_SINGLE_EPISODE_REQUEST';
export const GET_SINGLE_EPISODE_SUCCESS = 'GET_SINGLE_EPISODE_SUCCESS';
export const GET_SINGLE_EPISODE_FAIL = 'GET_SINGLE_EPISODE_FAIL';
export const SAVE_EPISODE_SUCCESS = 'SAVE_EPISODE_SUCCESS';
export const CLEAR_EPISODE = 'CLEAR_EPISODE';
export const CHANGE_EPISODE_DATA = 'CHANGE_EPISODE_DATA';
export const CANCEL_CHANGE_EPISODE_DATA = 'CANCEL_CHANGE_EPISODE_DATA';

