export const GET_SINGLE_COURSE_REQUEST = 'GET_SINGLE_COURSE_REQUEST';
export const GET_SINGLE_COURSE_SUCCESS = 'GET_SINGLE_COURSE_SUCCESS';
export const GET_SINGLE_COURSE_FAIL = 'GET_SINGLE_COURSE_FAIL';
export const ADD_AUTHOR_REQUEST = 'ADD_AUTHOR_REQUEST';
export const ADD_AUTHOR_SUCCESS = 'ADD_AUTHOR_SUCCESS';
export const ADD_AUTHOR_FAIL = 'ADD_AUTHOR_FAIL';
export const ADD_LESSON = 'ADD_LESSON';