export const SELECT_SUB_LESSON = 'SELECT_SUB_LESSON';
export const REMOVE_SUB_LESSON = 'REMOVE_SUB_LESSON';
export const MOVE_SUB_LESSON_UP = 'MOVE_SUB_LESSON_UP';
export const MOVE_SUB_LESSON_DOWN = 'MOVE_SUB_LESSON_DOWN';
export const ADD_SUB_LESSON = 'ADD_SUB_LESSON';