export const WORK_SHOP_LOAD_DATA = 'WORK_SHOP_LOAD_DATA';
export const WORK_SHOP_SAVE_DATA = 'WORK_SHOP_SAVE_DATA';
export const WORK_SHOP_GET_DATA_REQUEST = 'WORK_SHOP_GET_DATA_REQUEST';
export const WORK_SHOP_GET_DATA_SUCCESS = 'WORK_SHOP_GET_DATA_SUCCESS';
export const WORK_SHOP_GET_DATA_FAIL = 'WORK_SHOP_GET_DATA_FAIL';
export const WORK_SHOP_SHOW = 'WORK_SHOP_SHOW';
export const WORK_SHOP_HIDE = 'WORK_SHOP_HIDE';