export const course = {
    "Id": 17,
    "LanguageId": 1,
    "Cover": "2019/01/Madonna-di-Senigalliya-Ok-1474-Hudozhnik-Pero-della-Francheska-ital-Piero-della-Francesca-ok-1420-1492-Nacionalnaya-galereya-Marke-Urbino.jpg",
    "CoverMeta": "{\"mime-type\":\"image/jpeg\",\"path\":\"2019/01/\",\"content\":{\"s\":\"Madonna-di-Senigalliya-Ok-1474-Hudozhnik-Pero-della-Francheska-ital-Piero-della-Francesca-ok-1420-1492-Nacionalnaya-galereya-Marke-Urbino-360x423.jpg\",\"m\":\"Madonna-di-Senigalliya-Ok-1474-Hudozhnik-Pero-della-Francheska-ital-Piero-della-Francesca-ok-1420-1492-Nacionalnaya-galereya-Marke-Urbino-768x903.jpg\"},\"name\":\"Madonna-di-Senigalliya-Ok-1474-Hudozhnik-Pero-della-Francheska-ital-Piero-della-Francesca-ok-1420-1492-Nacionalnaya-galereya-Marke-Urbino\",\"size\":{\"width\":919,\"height\":1080},\"icon\":\"Madonna-di-Senigalliya-Ok-1474-Hudozhnik-Pero-della-Francheska-ital-Piero-della-Francesca-ok-1420-1492-Nacionalnaya-galereya-Marke-Urbino-150x176.jpg\"}",
    "OneLesson": false,
    "Mask": "_mask04",
    "Color": 12436683,
    "Name": "Русский канон в эпоху реализма",
    "ShortDescription": "Платный и емкий курс по основам  программирования. 7 коротких лекций помогут разобраться в " +
        "алгоритме создания digital-продукта и понять, какое место во всем процессе занимает каждый из компонентов: дизайн, верстка (html + css) и программирование. вы узнаете, в чём разница между html, css и javascript и за что отвечают разные языки программирования, напишете свои первые строки кода.",
    "Description": "Курс лекция о художниках, ваятелях, инженерах, архитекторах Кватроченто, то есть пятнадцатого века, 1400-х годов. Многие из них совмещали все эти знания и таланты. Осваивая линейную перспективу, оптику, механику и устройство человеческого тела, они создали замечательные памятники искусства, с которых многие специалисты и начинают, собственно, эпоху Возрождения. Ирина Языкова рассказывает о жизни и творчестве Филиппо Брунеллески, Лоренцо Гиберти, Донателло, Вероккьо, Паоло Уччелло и Фра Беато Анджелико, Андреа Мантенья и Доменико Гирландайо, Андреа дель Кастаньо, Пьеро делла Франческа, о художниках Умбрийской школы – Пинтуриккьо и Перуджино, а также о Джованни Беллини, Антонелла да Мессина и Сандро Боттичелли.",
    "TargetAudience": "Приступая к исследованию сущности души, Аристотель отбрасывает все те представления об этой сущности, которые он считает несостоятельными, ошибочными. ",
    "Aims": "Приступая к исследованию сущности души, Аристотель отбрасывает все те представления об этой сущности, которые он считает несостоятельными, ошибочными. Истина, полагает он, начинается с отказа от заблуждения. Поэтому в начале своего трактата \"О душе\" он последовательно излагает, а затем критикует все основные распространенные в его время учения о природе души. Уже в этом обзоре и в этой критике ярко выступает эмпирический характер психологии Аристотеля, его убеждение в тесной связи между душевными и телесными явлениями.",
    "URL": "quattrocento",
    "VideoIntwLink": null,
    "VideoIntroLink": "https://www.youtube.com/embed/QlQYipodc7s",
    "IntwD": null,
    "IntwDFmt": null,
    IntroD: 6174,
    IntroDFmt: "1:42:54",
    "IsSubsRequired": false,
    "ExtLinks": null,
    "IsBought": false,
    "IsPaid": true,
    "PaidTp": 1,
    "PaidDate": null,
    "IsGift": false,
    "IsPending": false,
    "IsSubsFree": false,
    "ProductId": 20,
    "Price": 2500,
    "DPrice": 2500,
    "Authors": [{
        "Id": 7,
        "FirstName": "Михаил",
        "LastName": "Свердлов",
        Portrait: "2017/10/Oleg_Voskoboinikov.jpg",
        "PortraitMeta": {content: {s: "Oleg_Voskoboinikov-360x503.jpg"},
            icon: "Oleg_Voskoboinikov-150x150.jpg",
            "mime-type": "image/jpeg",
            name: "Oleg_Voskoboinikov",
            path: "2017/10/",
            size: {width: 741, height: 1036}},
        "URL": "irina-yazykova",
        "Occupation": "Искуствовед",
        "Employment": "Преподает в крутом заведении",
        "Description": "Михаил Игоревич Свердлов — критик и литературовед, специалист по английской и русской литературе XIX–XX вв. Окончил МПГУ им. В. И. Ленина, учился в аспирантуре Литературного института имени М. Горького. В 1995 году защитил кандидатскую диссертацию по теме «Тема детства в английской оде XVII–XIX веков». В 1991–1995 годах — старший преподаватель кафедры культурологии МПГУ имени В. И. Ленина. С 1995 года — старший научный сотрудник Института мировой литературы имени М. Горького; в 2005 — 2008 годах редактор журнала «Вопросы литературы»; с 2012 года – доцент Школы филологии Факультета гуманитарных наук НИУ ВШЭ. Автор и редактор многочисленных книг о русской и зарубежной литературе, учебников для школ и гимназий. Публикует статьи в журналах «Вопросы литературы», «Новое литературное обозрение», «Новый мир» и др."
    }, {
        "Id": 7,
        "FirstName": "Надежда",
        "LastName": "Волкова",
        "Portrait": "2017/04/Irina_Yazykova2.jpg",
        "PortraitMeta": "{\"path\":\"2017/04/\",\"mime-type\":\"image/jpeg\",\"size\":{\"width\":691,\"height\":1036},\"content\":{\"s\":\"Irina_Yazykova2-360x540.jpg\"},\"icon\":\"Irina_Yazykova2-150x150.jpg\",\"name\":\"Irina_Yazykova2\"}",
        "URL": "irina-yazykova",
        "Occupation": "Историк философии",
        "Description": "Историк философии. В 2012 г. защитила кандидатскую диссертацию на тему «Душа как причина зла в философии Плотина». Научный сотрудник сектора Античной и средневековой философии и науки Института философии РАН. К сфере ее научных интересов относятся философия Платона и Аристотеля, средний платонизм (Плутарх Херонейский), неоплатонизм (Плотин), проблема зла и теодицеи, проблема индивидуации и др. Автор более 30-ти статей по истории античной философии."
    }],
    "Categories": [{"Id": 6, "Name": "Литература", "URL": "fine-arts"}],
    "Lessons": [{
        "Id": 142,
        "Number": 1,
        "ReadyDate": "2018-03-29T21:00:00.000Z",
        "State": "R",
        "ContentType": 1,
        "Cover": "2018/03/La-Cattedrale-di-Santa-Maria-del-Fiore-.jpg",
        "CoverMeta": "{\"path\":\"2018/03/\",\"mime-type\":\"image/jpeg\",\"size\":{\"width\":590,\"height\":464},\"content\":{\"s\":\"La-Cattedrale-di-Santa-Maria-del-Fiore--360x283.jpg\"},\"icon\":\"La-Cattedrale-di-Santa-Maria-del-Fiore--150x150.jpg\",\"name\":\"La Cattedrale di Santa Maria del Fiore\"}",
        "URL": "brunelleschi",
        "IsAuthRequired": false,
        "IsSubsRequired": false,
        "IsFreeInPaidCourse": false,
        "Name": "Новая перспектива Флоренции. Медичи. Филиппо Брунеллески",
        "ShortDescription": "Лекция о Флоренции, о семье Медичи, о художественном и инженерном творчестве Филиппо Брунеллески, создателе знаменитого купола флорентийского собора. ",
        "Duration": 2576,
        "DurationFmt": "42:56",
        "AuthorId": 7,
        "NSub": 2,
        "NRefBooks": 10,
        "NBooks": 0,
        "Lessons": [{
            "Id": 153,
            "Number": 1,
            "ReadyDate": "2018-06-05T21:00:00.000Z",
            "State": "R",
            "ContentType": 2,
            "Cover": "2018/06/Villa-di-Careggi.jpg",
            "CoverMeta": "{\"path\":\"2018/06/\",\"mime-type\":\"image/jpeg\",\"size\":{\"width\":1180,\"height\":1030},\"content\":{\"m\":\"Villa-di-Careggi-768x670.jpg\",\"s\":\"Villa-di-Careggi-360x314.jpg\"},\"icon\":\"Villa-di-Careggi-150x150.jpg\",\"name\":\"Villa di Careggi\"}",
            "URL": "medici",
            "IsAuthRequired": false,
            "IsSubsRequired": false,
            "IsFreeInPaidCourse": false,
            "Name": "Медичи",
            "ShortDescription": "Семейство Медичи и их роль в культуре Ренессанса.",
            "Duration": 630,
            "DurationFmt": "10:30",
            "AuthorId": 7,
            "NSub": 0,
            "NRefBooks": 0,
            "NBooks": 0,
            "Lessons": [],
            "Audios": ["2018/06/Yazykova_Quattrocento_Lec-01_Add-1_Mono_128Kbps_14-02-2018.mp3"],
            "Videos": []
        }, {
            "Id": 154,
            "Number": 2,
            "ReadyDate": "2018-06-29T21:00:00.000Z",
            "State": "R",
            "ContentType": 1,
            "Cover": "2018/06/Tempio-Malatestiano-in-Rimini.jpg",
            "CoverMeta": "{\"path\":\"2018/06/\",\"mime-type\":\"image/jpeg\",\"size\":{\"width\":590,\"height\":464},\"content\":{\"s\":\"Tempio-Malatestiano-in-Rimini-360x283.jpg\"},\"icon\":\"Tempio-Malatestiano-in-Rimini-150x150.jpg\",\"name\":\"Tempio Malatestiano in Rimini\"}",
            "URL": "alberti",
            "IsAuthRequired": false,
            "IsSubsRequired": false,
            "IsFreeInPaidCourse": false,
            "Name": "Альберти",
            "ShortDescription": "Разносторонняя ренессансная личность Леон Баттиста Альберти (1404–1472).",
            "Duration": 906,
            "DurationFmt": "15:06",
            "AuthorId": 7,
            "NSub": 0,
            "NRefBooks": 0,
            "NBooks": 0,
            "Lessons": [],
            "Audios": ["2018/06/Yazykova_Quattrocento_Lec-01_Add-2_Mono_128Kbps_18-04-2018.mp3"],
            "Videos": []
        }],
        "Audios": ["2018/03/Yazykova_Quattrocento_01_Brunelleschi_Mono_128Kbps_14-02-2018.mp3"],
        "Videos": []
    }, {
        "Id": 143,
        "Number": 2,
        "ReadyDate": "2018-04-18T21:00:00.000Z",
        "State": "R",
        "ContentType": 1,
        "Cover": "2018/03/Kolleoni-Stature-by-Verrocchio.jpg",
        "CoverMeta": "{\"path\":\"2018/03/\",\"mime-type\":\"image/jpeg\",\"size\":{\"width\":1180,\"height\":1030},\"content\":{\"m\":\"Kolleoni-Stature-by-Verrocchio-768x670.jpg\",\"s\":\"Kolleoni-Stature-by-Verrocchio-360x314.jpg\"},\"icon\":\"Kolleoni-Stature-by-Verrocchio-150x150.jpg\",\"name\":\"Kolleoni Stature by Verrocchio\"}",
        "URL": "great_sculptors_of_florence",
        "IsAuthRequired": false,
        "IsSubsRequired": false,
        "IsFreeInPaidCourse": false,
        "Name": "Великие скульпторы Флоренции: Донателло, Гиберти, Верроккьо",
        "ShortDescription": "Три знаменитых скульптора эпохи Кватроченто: Донателло, Лоренцо Гиберти и Андреа Верроккьо. ",
        "Duration": 3231,
        "DurationFmt": "53:51",
        "AuthorId": 7,
        "NSub": 1,
        "NRefBooks": 8,
        "NBooks": 0,
        "Lessons": [{
            "Id": 151,
            "Number": 1,
            "ReadyDate": "2018-05-22T21:00:00.000Z",
            "State": "R",
            "ContentType": 1,
            "Cover": "2018/05/Cantorial-pulpit-by-Luca-della-Robbia.jpg",
            "CoverMeta": "{\"path\":\"2018/05/\",\"mime-type\":\"image/jpeg\",\"size\":{\"width\":590,\"height\":464},\"content\":{\"s\":\"Cantorial-pulpit-by-Luca-della-Robbia-360x283.jpg\"},\"icon\":\"Cantorial-pulpit-by-Luca-della-Robbia-150x150.jpg\",\"name\":\"Cantorial pulpit by Luca della Robbia\"}",
            "URL": "luca_della_robbia",
            "IsAuthRequired": false,
            "IsSubsRequired": false,
            "IsFreeInPaidCourse": false,
            "Name": "Лука делла Роббиа",
            "ShortDescription": "Керамические и мраморные скульптуры Лука делла Роббиа. ",
            "Duration": 308,
            "DurationFmt": "5:08",
            "AuthorId": 7,
            "NSub": 0,
            "NRefBooks": 0,
            "NBooks": 0,
            "Lessons": [],
            "Audios": ["2018/05/Yazykova_Quattrocento_Lec-02_Add-1_Mono_128Kbps_22-02-2018.mp3"],
            "Videos": []
        }],
        "Audios": ["2018/03/Yazykova_Quattrocento_02_Sculpture_Mono_128Kbps_22-02-2018.mp3"],
        "Videos": []
    }, {
        "Id": 144,
        "Number": 3,
        "ReadyDate": "2018-04-26T21:00:00.000Z",
        "State": "R",
        "ContentType": 1,
        "Cover": "2018/03/Saint-George-and-the-Dragon-by-Uccello.jpg",
        "CoverMeta": "{\"path\":\"2018/03/\",\"mime-type\":\"image/jpeg\",\"size\":{\"width\":590,\"height\":464},\"content\":{\"s\":\"Saint-George-and-the-Dragon-by-Uccello-360x283.jpg\"},\"icon\":\"Saint-George-and-the-Dragon-by-Uccello-150x150.jpg\",\"name\":\"Saint George and the Dragon by Uccello\"}",
        "URL": "paolo_uccello",
        "IsAuthRequired": false,
        "IsSubsRequired": false,
        "IsFreeInPaidCourse": false,
        "Name": "Паоло Уччелло",
        "ShortDescription": "Работы Паоло ди Доно по прозванию Уччелло в жанрах фрески, батального панно, портрета и религиозной живописи.",
        "Duration": 1867,
        "DurationFmt": "31:07",
        "AuthorId": 7,
        "NSub": 0,
        "NRefBooks": 5,
        "NBooks": 0,
        "Lessons": [],
        "Audios": ["2018/03/Yazykova_Quattrocento_03_Uccello_Mono_128Kbps_16-03-2018.mp3"],
        "Videos": []
    }, {
        "Id": 150,
        "Number": 4,
        "ReadyDate": "2018-05-10T21:00:00.000Z",
        "State": "R",
        "ContentType": 1,
        "Cover": "2018/04/Annunciation-by-Fra-Angelico.jpg",
        "CoverMeta": "{\"path\":\"2018/04/\",\"mime-type\":\"image/jpeg\",\"size\":{\"width\":1180,\"height\":1030},\"content\":{\"m\":\"Annunciation-by-Fra-Angelico-768x670.jpg\",\"s\":\"Annunciation-by-Fra-Angelico-360x314.jpg\"},\"icon\":\"Annunciation-by-Fra-Angelico-150x150.jpg\",\"name\":\"Annunciation by Fra Angelico\"}",
        "URL": "fra_beato_angelico",
        "IsAuthRequired": false,
        "IsSubsRequired": false,
        "IsFreeInPaidCourse": false,
        "Name": "Фра Беато Анджелико",
        "ShortDescription": "Творчество доминиканца Джованни из Фьезоле, известного также как Брат Блаженный Ангельский.",
        "Duration": 2308,
        "DurationFmt": "38:28",
        "AuthorId": 7,
        "NSub": 2,
        "NRefBooks": 2,
        "NBooks": 0,
        "Lessons": [{
            "Id": 152,
            "Number": 1,
            "ReadyDate": "2018-05-29T21:00:00.000Z",
            "State": "R",
            "ContentType": 1,
            "Cover": "2018/05/Madonna-with-Dominic-and-Thomas-Aquinas-by-Fra-Beato-Angelico.jpg",
            "CoverMeta": "{\"path\":\"2018/05/\",\"mime-type\":\"image/jpeg\",\"size\":{\"width\":590,\"height\":464},\"content\":{\"s\":\"Madonna-with-Dominic-and-Thomas-Aquinas-by-Fra-Beato-Angelico-360x283.jpg\"},\"icon\":\"Madonna-with-Dominic-and-Thomas-Aquinas-by-Fra-Beato-Angelico-150x150.jpg\",\"name\":\"Madonna with Dominic and Thomas Aquinas by Fra Beato Angelico\"}",
            "URL": "saint_dominic_and_dominicans",
            "IsAuthRequired": false,
            "IsSubsRequired": false,
            "IsFreeInPaidCourse": false,
            "Name": "Доминик и доминиканцы",
            "ShortDescription": "Об основателе ордена проповедников св. Доминике, о роли доминиканцев в становлении Ренессанса и в последующей истории.",
            "Duration": 926,
            "DurationFmt": "15:26",
            "AuthorId": 7,
            "NSub": 0,
            "NRefBooks": 0,
            "NBooks": 0,
            "Lessons": [],
            "Audios": ["2018/05/Yazykova_Quattrocento_Lec-04_Add-1_Mono_128Kbps_17-03-2018.mp3"],
            "Videos": []
        }, {
            "Id": 155,
            "Number": 2,
            "ReadyDate": "2018-07-03T21:00:00.000Z",
            "State": "R",
            "ContentType": 1,
            "Cover": "2018/07/Dominican-Sisters-of-Blauvelt.jpg",
            "CoverMeta": "{\"path\":\"2018/07/\",\"mime-type\":\"image/jpeg\",\"size\":{\"width\":590,\"height\":464},\"content\":{\"s\":\"Dominican-Sisters-of-Blauvelt-360x283.jpg\"},\"icon\":\"Dominican-Sisters-of-Blauvelt-150x150.jpg\",\"name\":\"Dominican Sisters of Blauvelt\"}",
            "URL": "third-order-of-dominicans",
            "IsAuthRequired": false,
            "IsSubsRequired": false,
            "IsFreeInPaidCourse": false,
            "Name": "Братья и сестры покаяния",
            "ShortDescription": "Терциарии доминиканского ордена.",
            "Duration": 69,
            "DurationFmt": "1:09",
            "AuthorId": 7,
            "NSub": 0,
            "NRefBooks": 0,
            "NBooks": 0,
            "Lessons": [],
            "Audios": ["2018/07/Yazykova_Quattrocento_Lec-04_Add-2_Mono_128Kbps_17-03-2018.mp3"],
            "Videos": []
        }],
        "Audios": ["2018/04/Yazykova_Quattrocento_04_FraAngelico_Mono_128Kbps_16-03-2018.mp3"],
        "Videos": []
    }, {
        "Id": 145,
        "Number": 5,
        "ReadyDate": "2018-05-24T21:00:00.000Z",
        "State": "R",
        "ContentType": 1,
        "Cover": "2018/03/Piet-by-Giovanni-Bellini.jpg",
        "CoverMeta": "{\"path\":\"2018/03/\",\"mime-type\":\"image/jpeg\",\"size\":{\"width\":1180,\"height\":1030},\"content\":{\"m\":\"Piet-by-Giovanni-Bellini-768x670.jpg\",\"s\":\"Piet-by-Giovanni-Bellini-360x314.jpg\"},\"icon\":\"Piet-by-Giovanni-Bellini-150x150.jpg\",\"name\":\"Pietà by Giovanni Bellini\"}",
        "URL": "mantegna_and_bellini",
        "IsAuthRequired": false,
        "IsSubsRequired": false,
        "IsFreeInPaidCourse": false,
        "Name": "Художник в поисках своего лица: Андреа Мантенья и Джованни Беллини",
        "ShortDescription": "Творчество мантуанца Андреа Мантенья и его свойственников из венецианского клана Беллини.",
        "Duration": 2563,
        "DurationFmt": "42:43",
        "AuthorId": 7,
        "NSub": 1,
        "NRefBooks": 10,
        "NBooks": 0,
        "Lessons": [{
            "Id": 157,
            "Number": 1,
            "ReadyDate": "2018-07-27T21:00:00.000Z",
            "State": "R",
            "ContentType": 1,
            "Cover": "2018/07/Madonna-of-Chancellor-Rolin.jpg",
            "CoverMeta": "{\"path\":\"2018/07/\",\"mime-type\":\"image/jpeg\",\"size\":{\"width\":590,\"height\":464},\"content\":{\"s\":\"Madonna-of-Chancellor-Rolin-360x283.jpg\"},\"icon\":\"Madonna-of-Chancellor-Rolin-150x150.jpg\",\"name\":\"Madonna of Chancellor Rolin\"}",
            "URL": "oil-paints-epoch",
            "IsAuthRequired": false,
            "IsSubsRequired": false,
            "IsFreeInPaidCourse": false,
            "Name": "Эпоха масла",
            "ShortDescription": "В эпоху Кватроченто на смену темперной живописи приходят масляные краски.",
            "Duration": 495,
            "DurationFmt": "8:15",
            "AuthorId": 7,
            "NSub": 0,
            "NRefBooks": 0,
            "NBooks": 0,
            "Lessons": [],
            "Audios": ["2018/07/Yazykova_Quattrocento_Lec-05_Add-1_Mono_128Kbps_18-04-2018.mp3"],
            "Videos": []
        }],
        "Audios": ["2018/03/Yazykova_Quattrocento_05_Mantegna_and_Bellini_Mono_128Kbps_18-04-2018.mp3"],
        "Videos": []
    }, {
        "Id": 146,
        "Number": 6,
        "ReadyDate": "2018-06-07T21:00:00.000Z",
        "State": "R",
        "ContentType": 1,
        "Cover": "2018/03/Angels-from-Christmas-by-Piero-della-Francesca.jpg",
        "CoverMeta": "{\"path\":\"2018/03/\",\"mime-type\":\"image/jpeg\",\"size\":{\"width\":590,\"height\":464},\"content\":{\"s\":\"Angels-from-Christmas-by-Piero-della-Francesca-360x283.jpg\"},\"icon\":\"Angels-from-Christmas-by-Piero-della-Francesca-150x150.jpg\",\"name\":\"Angels from Christmas by Piero della Francesca\"}",
        "URL": "piero_della_francesca",
        "IsAuthRequired": false,
        "IsSubsRequired": false,
        "IsFreeInPaidCourse": false,
        "Name": "Пьеро делла Франческа — образ человеческого достоинства",
        "ShortDescription": "Труды, города, заказчики и загадки Пьетро, сына Франчески, из Борго-Сан-Сеполькро. ",
        "Duration": 2652,
        "DurationFmt": "44:12",
        "AuthorId": 7,
        "NSub": 1,
        "NRefBooks": 5,
        "NBooks": 0,
        "Lessons": [{
            "Id": 156,
            "Number": 1,
            "ReadyDate": "2018-07-22T21:00:00.000Z",
            "State": "R",
            "ContentType": 1,
            "Cover": "2018/07/Adams-death-by-Piero-della-Francesca.jpg",
            "CoverMeta": "{\"path\":\"2018/07/\",\"mime-type\":\"image/jpeg\",\"size\":{\"width\":590,\"height\":464},\"content\":{\"s\":\"Adams-death-by-Piero-della-Francesca-360x283.jpg\"},\"icon\":\"Adams-death-by-Piero-della-Francesca-150x150.jpg\",\"name\":\"Adam's death by Piero della Francesca\"}",
            "URL": "history-of-cross",
            "IsAuthRequired": false,
            "IsSubsRequired": false,
            "IsFreeInPaidCourse": false,
            "Name": "История Креста",
            "ShortDescription": "Серия фресок Пьеро делла Франческа в Ареццо с легендарной «Историей Животворящего Креста».",
            "Duration": 1001,
            "DurationFmt": "16:41",
            "AuthorId": 7,
            "NSub": 0,
            "NRefBooks": 0,
            "NBooks": 0,
            "Lessons": [],
            "Audios": ["2018/07/Yazykova_Quattrocento_Lec-06_Add-1_Mono_128Kbps_31-05-2018.mp3"],
            "Videos": []
        }],
        "Audios": ["2018/03/Yazykova_Quattrocento_06_Piero_della_Francesca_Mono_128Kbps_08-05-2018.mp3"],
        "Videos": []
    }, {
        "Id": 147,
        "Number": 7,
        "ReadyDate": "2018-06-21T21:00:00.000Z",
        "State": "R",
        "ContentType": 1,
        "Cover": "2018/03/Delivery-of-the-Keys-by-Perugino-.jpg",
        "CoverMeta": "{\"path\":\"2018/03/\",\"mime-type\":\"image/jpeg\",\"size\":{\"width\":1180,\"height\":1030},\"content\":{\"m\":\"Delivery-of-the-Keys-by-Perugino--768x670.jpg\",\"s\":\"Delivery-of-the-Keys-by-Perugino--360x314.jpg\"},\"icon\":\"Delivery-of-the-Keys-by-Perugino--150x150.jpg\",\"name\":\"Delivery of the Keys by Perugino\"}",
        "URL": "rinascimento_umbro",
        "IsAuthRequired": false,
        "IsSubsRequired": false,
        "IsFreeInPaidCourse": false,
        "Name": "Умбрийская школа: Пьетро Перуджино и Пинтуриккио",
        "ShortDescription": "Представители Умбрийской школы живописи – Пьетро Перуджино и Пинтуриккио. ",
        "Duration": 2150,
        "DurationFmt": "35:50",
        "AuthorId": 7,
        "NSub": 0,
        "NRefBooks": 7,
        "NBooks": 0,
        "Lessons": [],
        "Audios": ["2018/03/Yazykova_Quattrocento_07_Rinascimento_umbro_Mono_128Kbps_31-05-2018.mp3"],
        "Videos": []
    }, {
        "Id": 148,
        "Number": 8,
        "ReadyDate": "2018-07-05T21:00:00.000Z",
        "State": "R",
        "ContentType": 1,
        "Cover": "2018/03/Three-angels-and-Tobit-by-Filippino-Lippi.jpg",
        "CoverMeta": "{\"path\":\"2018/03/\",\"mime-type\":\"image/jpeg\",\"size\":{\"width\":590,\"height\":464},\"content\":{\"s\":\"Three-angels-and-Tobit-by-Filippino-Lippi-360x283.jpg\"},\"icon\":\"Three-angels-and-Tobit-by-Filippino-Lippi-150x150.jpg\",\"name\":\"Three angels and Tobit by Filippino Lippi\"}",
        "URL": "filippo-lippi",
        "IsAuthRequired": false,
        "IsSubsRequired": false,
        "IsFreeInPaidCourse": false,
        "Name": "Филиппо Липпи",
        "ShortDescription": "Лекция о неудавшемся монахе и состоявшемся художнике Филиппо Липпи, который был учеником Мазаччо и учителем Боттичелли.",
        "Duration": 1312,
        "DurationFmt": "21:52",
        "AuthorId": 7,
        "NSub": 0,
        "NRefBooks": 4,
        "NBooks": 0,
        "Lessons": [],
        "Audios": ["2018/03/Yazykova_Quattrocento_08_Filippo_Lippi_Mono_128Kbps_22-06-2018.mp3"],
        "Videos": []
    }, {
        "Id": 149,
        "Number": 9,
        "ReadyDate": "2018-08-02T21:00:00.000Z",
        "State": "R",
        "ContentType": 1,
        "Cover": "2018/03/The-Birth-of-Venus.jpg",
        "CoverMeta": "{\"path\":\"2018/03/\",\"mime-type\":\"image/jpeg\",\"size\":{\"width\":590,\"height\":464},\"content\":{\"s\":\"The-Birth-of-Venus-360x283.jpg\"},\"icon\":\"The-Birth-of-Venus-150x150.jpg\",\"name\":\"The Birth of Venus\"}",
        "URL": "sandro-botticelli",
        "IsAuthRequired": false,
        "IsSubsRequired": false,
        "IsFreeInPaidCourse": false,
        "Name": "Сандро Боттичелли",
        "ShortDescription": "Творческий путь и особое место Боттичелли в культуре Возрождения. ",
        "Duration": 3284,
        "DurationFmt": "54:44",
        "AuthorId": 7,
        "NSub": 1,
        "NRefBooks": 8,
        "NBooks": 0,
        "Lessons": [{
            "Id": 158,
            "Number": 1,
            "ReadyDate": "2018-08-07T21:00:00.000Z",
            "State": "R",
            "ContentType": 1,
            "Cover": "2018/08/Journey-of-the-Magi-by-Benozzo-Gozzoli-fragm.jpg",
            "CoverMeta": "{\"path\":\"2018/08/\",\"mime-type\":\"image/jpeg\",\"size\":{\"width\":1180,\"height\":1030},\"content\":{\"m\":\"Journey-of-the-Magi-by-Benozzo-Gozzoli-fragm-768x670.jpg\",\"s\":\"Journey-of-the-Magi-by-Benozzo-Gozzoli-fragm-360x314.jpg\"},\"icon\":\"Journey-of-the-Magi-by-Benozzo-Gozzoli-fragm-150x150.jpg\",\"name\":\"Journey of the Magi by Benozzo Gozzoli (fragm)\"}",
            "URL": "birth-of-portrait",
            "IsAuthRequired": false,
            "IsSubsRequired": false,
            "IsFreeInPaidCourse": false,
            "Name": "Рождение портрета",
            "ShortDescription": "Зарождение и эволюция портретного жанра в эпоху Ренессанса.",
            "Duration": 1285,
            "DurationFmt": "21:25",
            "AuthorId": 7,
            "NSub": 0,
            "NRefBooks": 0,
            "NBooks": 0,
            "Lessons": [],
            "Audios": ["2018/08/Yazykova_Quattrocento_Lec-09_Add-1_Mono_128Kbps_06-07-2018.mp3"],
            "Videos": []
        }],
        "Audios": ["2018/03/Yazykova_Quattrocento_09_Sandro_Botticelli_Mono_128Kbps_22-06-2018.mp3"],
        "Videos": []
    }],
    "Books": [{
        Authors: [{
            FirstName: "Олег",
            Id: 8,
            LastName: "Лекманов",
            Tp: 1,
            TpView: 2,
            URL: "sinelnikov"
        }],
        CourseId: 25,
        Cover: "2019/03/P71203-112541-f88609f5-ee83-4ccd-889b-7fc759cc19b1.jpg",
        CoverMeta: {"mime-type":"image/jpeg",
            "path":"2019/03/",
            "content":{"s":"P71203-112541-f88609f5-ee83-4ccd-889b-7fc759cc19b1-360x486.jpg","m":"P71203-112541-f88609f5-ee83-4ccd-889b-7fc759cc19b1-768x1036.jpg","l":"P71203-112541-f88609f5-ee83-4ccd-889b-7fc759cc19b1-1366x1842.jpg"},"name":"P71203-112541","size":{"width":3120,"height":4208},"icon":"P71203-112541-f88609f5-ee83-4ccd-889b-7fc759cc19b1-150x202.jpg"},
        Description: "Перед вами сборник лекций известного российского литературоведа, в основе которого – курс, прочитанный в 2017 году для образовательного проекта «Магистерия». Настоящее издание – первое в книжной серии, в которой российские ученые будут коротко и популярно рассказывать о самом важном в истории культуры.",
        ExtLinks: {
            "www.ozon.ru": "https://www.storytel.com/ru/ru/books/553175-Ne-zhizn-a-skazka",
            "www.labirint.ru": "https://www.storytel.com/ru/ru/books/553175-Ne-zhizn-a-skazka",
            "ru.bookmate.com": "https://www.storytel.com/ru/ru/books/553175-Ne-zhizn-a-skazka",
        },
        Id: 6,
        Name: "Ключи к Серебряному веку",
        OtherAuthors: null,
        OtherCAuthors: null,
    }],
    "RefBooks": [],
    "ShareCounters": {},
    "PageMeta": {}
}