export const COURSES = {
    HIGH_RENAISSANCE: {
        "Id": 24,
        "LanguageId": 1,
        "Cover": "2019/10/1-32-5e3a91ef-a68d-40e3-b91e-b00d916c9c42.jpg",
        "CoverMeta": "{\"mime-type\":\"image/jpeg\",\"path\":\"2019/10/\",\"content\":{\"s\":\"1-32-5e3a91ef-a68d-40e3-b91e-b00d916c9c42-360x203.jpg\",\"m\":\"1-32-5e3a91ef-a68d-40e3-b91e-b00d916c9c42-768x432.jpg\",\"l\":\"1-32-5e3a91ef-a68d-40e3-b91e-b00d916c9c42-1366x768.jpg\"},\"name\":\"1 (32)\",\"size\":{\"width\":1920,\"height\":1080},\"icon\":\"1-32-5e3a91ef-a68d-40e3-b91e-b00d916c9c42-150x84.jpg\"}",
        "LandCover": "2020/04/1-48-cdfbcebc-02a3-4c52-8cd4-bdcd9948d650.jpg",
        "LandCoverMeta": "{\"mime-type\":\"image/jpeg\",\"path\":\"2020/04/\",\"content\":{\"s\":\"1-48-cdfbcebc-02a3-4c52-8cd4-bdcd9948d650-360x203.jpg\",\"m\":\"1-48-cdfbcebc-02a3-4c52-8cd4-bdcd9948d650-768x432.jpg\",\"l\":\"1-48-cdfbcebc-02a3-4c52-8cd4-bdcd9948d650-1366x768.jpg\"},\"name\":\"1 (48)\",\"size\":{\"width\":1920,\"height\":1080},\"icon\":\"1-48-cdfbcebc-02a3-4c52-8cd4-bdcd9948d650-150x84.jpg\",\"backgroundPosition\":{\"absolute\":{\"top\":84,\"left\":134.078125},\"percent\":{\"top\":0.4148148148148148,\"left\":0.3724392361111111}}}",
        "IsLandingPage": true,
        "OneLesson": false,
        "Mask": "_mask04",
        "Color": 13421765,
        "Name": "Высокое Возрождение",
        "Description": "На смену равновесию небесного и земного, божественного и человеческого, на смену гармонии, достигнутой мастерами эпохи Кватроченто приходит мятежный XVI век – век Реформации и Контрреформации, революционных открытий и религиозных войн, но также и век Высокого Ренессанса. Итальянское и, шире, европейское искусство достигло своей высшей точки. Дальше ему предстоит какой-то новый путь, по всей видимости, долгий и извилистый спуск в долину. Но на вершине мы встречаем подлинных титанов, универсальных людей, многие из которых были одновременно живописцами, скульпторами, архитекторами, философами, естествоиспытателями, изобретателями. Их творчеству и посвящен третий курс Ирины Языковой из серии, в первой части которой шла речь о Проторенессансе, а во второй – о пятнадцатом столетии. Рафаэль, Леонардо, Микеланджело, Джорджоне, Тициан, Веронезе и Тинторетто, а также мастера последующей эпохи маньеризма – вот главные герои курса «Высокое Возрождение».",
        "CourseType": 1,
        "URL": "high-renaissance",
        "VideoIntwLink": null,
        "VideoIntroLink": null,
        "ShortDescription": "На смену равновесию небесного и земного, божественного и человеческого, на смену гармонии, достигнутой мастерами эпохи Кватроченто приходит мятежный XVI век – век Реформации и Контрреформации, революционных открытий и религиозных войн, но также и век Высокого Ренессанса. Итальянское и, шире, европейское искусство достигло своей высшей точки. Дальше ему предстоит какой-то новый путь, по всей видимости, долгий и извилистый спуск в долину. Но на вершине мы встречаем подлинных титанов, универсальных людей, многие из которых были одновременно живописцами, скульпторами, архитекторами, философами, естествоиспытателями, изобретателями. Их творчеству и посвящен третий курс Ирины Языковой из серии, в первой части которой шла речь о Проторенессансе, а во второй – о пятнадцатом столетии. Рафаэль, Леонардо, Микеланджело, Джорджоне, Тициан, Веронезе и Тинторетто, а также мастера последующей эпохи маньеризма – вот главные герои курса «Высокое Возрождение».",
        "TargetAudience": "Всем",
        "Aims": "Всему",
        "EstDuration": 43200,
        "IntwD": 0,
        "IntwDFmt": "",
        "IntroD": 0,
        "IntroDFmt": "",
        "IsSubsRequired": false,
        "ExtLinks": null,
        "IsBought": false,
        "IsPaid": true,
        "PaidTp": 1,
        "PaidDate": null,
        "IsGift": false,
        "IsPending": false,
        "IsSubsFree": false,
        "ProductId": 10,
        "Price": 1500,
        "DPrice": 1200,
        "Authors": [{
            "Id": 7,
            "FirstName": "Ирина",
            "LastName": "Языкова",
            "Description": "Искусствовед, кандидат культурологии. Окончила Московский Государственный Университет им. Ломоносова, исторический факультет, отделение истории искусства. Специалист по христианской культуре, в частности, по древней и современной иконописи. Кандидатская диссертация на тему \"Икона в ХХ веке\". Преподает в Библейско-богословском институте св. апостола Андрея и Коломенской духовной семинарии, читает публичные лекции по искусству. Автор нескольких монографий и многих статей.",
            "ShortDescription": null,
            "Occupation": null,
            "Employment": null,
            "Portrait": "2017/04/Irina_Yazykova2.jpg",
            "PortraitMeta": "{\"path\":\"2017/04/\",\"mime-type\":\"image/jpeg\",\"size\":{\"width\":691,\"height\":1036},\"content\":{\"s\":\"Irina_Yazykova2-360x540.jpg\"},\"icon\":\"Irina_Yazykova2-150x150.jpg\",\"name\":\"Irina_Yazykova2\"}",
            "URL": "irina-yazykova"
        }],
        "Categories": [{"Id": 6, "Name": "Искусство", "URL": "fine-arts"}],
        "Lessons": [{
            "Id": 159,
            "Number": 1,
            "ReadyDate": "2018-10-11T21:00:00.000Z",
            "State": "R",
            "ContentType": 1,
            "Cover": "2018/10/St-Peters-Cathedral.jpg",
            "CoverMeta": "{\"path\":\"2018/10/\",\"mime-type\":\"image/jpeg\",\"size\":{\"width\":1180,\"height\":1030},\"content\":{\"m\":\"St-Peters-Cathedral-768x670.jpg\",\"s\":\"St-Peters-Cathedral-360x314.jpg\"},\"icon\":\"St-Peters-Cathedral-150x150.jpg\",\"name\":\"St Peters Cathedral\"}",
            "URL": "second-wave",
            "IsAuthRequired": false,
            "IsSubsRequired": false,
            "IsFreeInPaidCourse": false,
            "IsFinished": false,
            "Name": "Высокое Возрождение – вторая волна",
            "ShortDescription": "Вводная лекция о Высоком Возрождении – это взгляд на XVI век с высоты птичьего полета, обзор драматических событий, расколов и реформ, на фоне которых создавалось искусство великих мастеров. ",
            "Duration": 3021,
            "DurationFmt": "50:21",
            "AuthorId": 7,
            "NSub": 0,
            "NRefBooks": 10,
            "NBooks": 0,
            "Lessons": [],
            "Audios": ["2018/10/Yazykova_HRenaissance_01_Intro_Mono_128Kbps_14-09-2018.mp3"],
            "Videos": []
        }, {
            "Id": 160,
            "Number": 2,
            "ReadyDate": "2018-10-25T21:00:00.000Z",
            "State": "R",
            "ContentType": 1,
            "Cover": "2018/10/The-Deposition-by-Raphael.jpg",
            "CoverMeta": "{\"path\":\"2018/10/\",\"mime-type\":\"image/jpeg\",\"size\":{\"width\":1180,\"height\":1030},\"content\":{\"m\":\"The-Deposition-by-Raphael-768x670.jpg\",\"s\":\"The-Deposition-by-Raphael-360x314.jpg\"},\"icon\":\"The-Deposition-by-Raphael-150x150.jpg\",\"name\":\"The Deposition by Raphael\"}",
            "URL": "raphael",
            "IsAuthRequired": false,
            "IsSubsRequired": false,
            "IsFreeInPaidCourse": false,
            "IsFinished": false,
            "Name": "Рафаэль — певец гармонии",
            "ShortDescription": "Творчество и жизнь безоблачного и загадочного Рафаэля Санти.",
            "Duration": 3539,
            "DurationFmt": "58:59",
            "AuthorId": 7,
            "NSub": 0,
            "NRefBooks": 15,
            "NBooks": 0,
            "Lessons": [],
            "Audios": ["2018/10/Yazykova_HRenaissance_02_Raphael_Mono_128Kbps_24-09-2018.mp3"],
            "Videos": []
        }, {
            "Id": 161,
            "Number": 3,
            "ReadyDate": "2018-11-08T21:00:00.000Z",
            "State": "R",
            "ContentType": 1,
            "Cover": "2018/10/Kopiya-kartona-Leonardo-da-Vinchi-Bitva-pri-Angiari-.-Pieter-Paul-Rubens.jpg",
            "CoverMeta": "{\"path\":\"2018/10/\",\"mime-type\":\"image/jpeg\",\"size\":{\"width\":590,\"height\":464},\"content\":{\"s\":\"Kopiya-kartona-Leonardo-da-Vinchi-Bitva-pri-Angiari-.-Pieter-Paul-Rubens-360x283.jpg\"},\"icon\":\"Kopiya-kartona-Leonardo-da-Vinchi-Bitva-pri-Angiari-.-Pieter-Paul-Rubens-150x150.jpg\",\"name\":\"Копия картона Леонардо да Винчи «Битва при Ангиари». Pieter Paul Rubens\"}",
            "URL": "leonardo",
            "IsAuthRequired": false,
            "IsSubsRequired": false,
            "IsFreeInPaidCourse": false,
            "IsFinished": false,
            "Name": "Леонардо — художник, ученый, философ",
            "ShortDescription": "Скрытный мастер незаконченных произведений и его знаменитые работы.",
            "Duration": 3201,
            "DurationFmt": "53:21",
            "AuthorId": 7,
            "NSub": 0,
            "NRefBooks": 15,
            "NBooks": 0,
            "Lessons": [],
            "Audios": ["2018/10/Yazykova_HRenaissance_03_Leonardo_Mono_128Kbps_01-10-2018.mp3"],
            "Videos": []
        }, {
            "Id": 162,
            "Number": 4,
            "ReadyDate": "2018-11-29T21:00:00.000Z",
            "State": "D",
            "ContentType": 1,
            "Cover": null,
            "CoverMeta": null,
            "URL": "mikelandzhelo-tragicheskij-prorok",
            "IsAuthRequired": false,
            "IsSubsRequired": false,
            "IsFreeInPaidCourse": false,
            "IsFinished": false,
            "Name": "Микеланджело — трагический пророк",
            "ShortDescription": "",
            "Duration": 0,
            "DurationFmt": "00:00",
            "AuthorId": 7,
            "NSub": 0,
            "NRefBooks": 0,
            "NBooks": 0,
            "Lessons": [],
            "Audios": [],
            "Videos": []
        }, {
            "Id": 163,
            "Number": 5,
            "ReadyDate": "2018-12-30T21:00:00.000Z",
            "State": "D",
            "ContentType": 1,
            "Cover": null,
            "CoverMeta": null,
            "URL": "venetsianskaya-osen-dzhordzhone",
            "IsAuthRequired": false,
            "IsSubsRequired": false,
            "IsFreeInPaidCourse": false,
            "IsFinished": false,
            "Name": "Венецианская осень. Джорджоне",
            "ShortDescription": "",
            "Duration": 0,
            "DurationFmt": "00:00",
            "AuthorId": 7,
            "NSub": 0,
            "NRefBooks": 0,
            "NBooks": 0,
            "Lessons": [],
            "Audios": [],
            "Videos": []
        }, {
            "Id": 164,
            "Number": 6,
            "ReadyDate": "2018-12-30T21:00:00.000Z",
            "State": "D",
            "ContentType": 1,
            "Cover": null,
            "CoverMeta": null,
            "URL": "tsvet-i-svet-v-zhivopisi-titsiana",
            "IsAuthRequired": false,
            "IsSubsRequired": false,
            "IsFreeInPaidCourse": false,
            "IsFinished": false,
            "Name": "Цвет и свет в живописи Тициана",
            "ShortDescription": "",
            "Duration": 0,
            "DurationFmt": "00:00",
            "AuthorId": 7,
            "NSub": 0,
            "NRefBooks": 0,
            "NBooks": 0,
            "Lessons": [],
            "Audios": [],
            "Videos": []
        }, {
            "Id": 165,
            "Number": 7,
            "ReadyDate": "2019-12-30T21:00:00.000Z",
            "State": "D",
            "ContentType": 1,
            "Cover": null,
            "CoverMeta": null,
            "URL": "posle-vozrozhdeniya-veroneze-i-tintoretto",
            "IsAuthRequired": false,
            "IsSubsRequired": false,
            "IsFreeInPaidCourse": false,
            "IsFinished": false,
            "Name": "После Возрождения. Веронезе и Тинторетто",
            "ShortDescription": "",
            "Duration": 0,
            "DurationFmt": "00:00",
            "AuthorId": 7,
            "NSub": 0,
            "NRefBooks": 0,
            "NBooks": 0,
            "Lessons": [],
            "Audios": [],
            "Videos": []
        }, {
            "Id": 166,
            "Number": 8,
            "ReadyDate": "2019-12-30T21:00:00.000Z",
            "State": "D",
            "ContentType": 1,
            "Cover": null,
            "CoverMeta": null,
            "URL": "manerizm-v-poiskah-utrachennoj-garmonii",
            "IsAuthRequired": false,
            "IsSubsRequired": false,
            "IsFreeInPaidCourse": false,
            "IsFinished": false,
            "Name": "Маньеризм: в поисках утраченной гармонии",
            "ShortDescription": "",
            "Duration": 0,
            "DurationFmt": "00:00",
            "AuthorId": 7,
            "NSub": 0,
            "NRefBooks": 0,
            "NBooks": 0,
            "Lessons": [],
            "Audios": [],
            "Videos": []
        }],
        "Books": [],
        "RefBooks": [],
        "ShareCounters": {},
        "PageMeta": {"Name": "Курс", "Description": "Описание", "Post": "Текст", "Images": {}},
        "Tests": [],
        "Discount": {
            "Description": "Тестовая скидка",
            "Perc": 20,
            "FirstDate": "2020-06-21T21:00:00.000Z",
            "LastDate": "2020-06-28T21:00:00.000Z"
        },
        PersonalDiscounts: {
            "pos970": {
                Perc: 30,
                Hours: 48,
                Price: 1050,
                LastDate: "2020-06-28T21:00:00.000Z"
            }
        },
        "Reviews": [{
            "Id": 39,
            "ReviewDate": "2020-05-15T10:00:34.000Z",
            "UserId": 2,
            "Status": 1,
            "UserName": "Alexander Staloverov",
            "ProfileUrl": null,
            "Title": null,
            "ReviewPub": "Сейчас масса автомобильных концернов выпускают автомобили в различных бюджетных категориях. При этом одни бьют рекорды популярности, а другие годами остаются невостребованными.\n\nЯ же хочу поговорить о тех моделях, которые даже если были востребованы новенькими, то на вторичке их не сильно расхватывают. А точнее, они вообще не пользуются спросом – неликвидны. Эти четыре автомобиля лучше знать, чтобы не вляпаться в это неликвидное железо."
        }, {
            "Id": 38,
            "ReviewDate": "2020-05-15T09:58:47.000Z",
            "UserId": 2,
            "Status": 1,
            "UserName": "Alexander Staloverov",
            "ProfileUrl": "https://www.facebook.com/profile.php?id=100001888774550",
            "Title": null,
            "ReviewPub": "«Я не вижу никакой необходимости и не слышал ни о каких планах подобного рода среди людей, которые имеют мало-мальское отношение к принятию соответствующих решений», — сказал глава российского внешнеполитического ведомства в ответ на соответствующий вопрос. \n\nРанее исполнительный директор Ассоциации туроператоров России Майя Ломидзе в беседе с НСН оценила прогнозы по открытию границ в мире."
        }]
    }
}
