export const SHOW_ADD_AUTHOR_DIALOG = 'SHOW_ADD_AUTHOR_DIALOG';
export const HIDE_ADD_AUTHOR_DIALOG = 'HIDE_ADD_AUTHOR_DIALOG';
export const SELECT_COURSE_AUTHOR = 'SELECT_COURSE_AUTHOR';
export const ADD_AUTHOR = 'ADD_AUTHOR';
export const REMOVE_AUTHOR = 'REMOVE_AUTHOR';