// export const GET_COURSE_LESSONS_SUCCESS = 'GET_COURSE_LESSONS_SUCCESS';
// export const GET_COURSE_LESSONS_SUCCESS = 'GET_COURSE_LESSONS_SUCCESS';
// export const MOVE_LESSON_UP = 'MOVE_LESSON_UP';
// export const MOVE_LESSON_DOWN = 'MOVE_LESSON_DOWN';

export const SELECT_COURSE_LESSON = 'SELECT_COURSE_LESSON';
export const ADD_LESSON = 'ADD_LESSON';
export const REMOVE_LESSON = 'REMOVE_LESSON';
export const MOVE_LESSON_UP = 'MOVE_LESSON_UP';
export const MOVE_LESSON_DOWN = 'MOVE_LESSON_DOWN';