export const SHOW_ADD_CATEGORY_DIALOG = 'SHOW_ADD_CATEGORY_DIALOG';
export const SELECT_COURSE_CATEGORY = 'SELECT_COURSE_CATEGORY';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const REMOVE_CATEGORY = 'REMOVE_CATEGORY';
export const HIDE_ADD_CATEGORY_DIALOG = 'HIDE_ADD_CATEGORY_DIALOG';