export const CREATE_NEW_COURSE = 'CREATE_NEW_COURSE';
export const GET_SINGLE_COURSE_REQUEST = 'GET_SINGLE_COURSE_REQUEST';
export const GET_SINGLE_COURSE_SUCCESS = 'GET_SINGLE_COURSE_SUCCESS';
export const GET_SINGLE_COURSE_FAIL = 'GET_SINGLE_COURSE_FAIL';
export const CHANGE_COURSE_DATA = 'CHANGE_COURSE_DATA';
export const CANCEL_CHANGE_COURSE_DATA = 'CANCEL_CHANGE_COURSE_DATA';
export const CLEAR_COURSE='CLEAR_COURSE';

export const SAVE_COURSE_START = 'SAVE_COURSE_START';
export const SAVE_COURSE_SUCCESS = 'SAVE_COURSE_SUCCESS';
export const SAVE_COURSE_FAIL = 'SAVE_COURSE_FAIL';