export const CREATE_RESOURCE = 'CREATE_RESOURCE';
export const EDIT_RESOURCE = 'EDIT_RESOURCE';
export const CLEAR_RESOURCE = 'CLEAR_RESOURCE';
export const MULTI_UPLOAD_RESOURCES_START = 'MULTI_UPLOAD_RESOURCES_START';
export const MULTI_UPLOAD_RESOURCES_CANCEL = 'MULTI_UPLOAD_RESOURCES_CANCEL';
export const MULTI_UPLOAD_RESOURCES_FINISH = 'MULTI_UPLOAD_RESOURCES_FINISH';

export const SELECT_RESOURCE = 'SELECT_RESOURCE';
export const INSERT_RESOURCE = 'INSERT_RESOURCE';
export const MULTIPLE_INSERT_RESOURCE = 'MULTIPLE_INSERT_RESOURCE';
export const UPDATE_RESOURCE = 'UPDATE_RESOURCE';
export const REMOVE_RESOURCE = 'REMOVE_RESOURCE';
export const MOVE_RESOURCE_UP = 'MOVE_RESOURCE_UP';
export const MOVE_RESOURCE_DOWN = 'MOVE_RESOURCE_DOWN';

export const SELECT_SN_IMAGE_START = 'SELECT_SN_IMAGE_START';
export const SELECT_SN_IMAGE_FINISH = 'SELECT_SN_IMAGE_FINISH';
