export const SHOW_ERROR_DIALOG = "SHOW_ERROR_DIALOG";
export const HIDE_ERROR_DIALOG = "HIDE_ERROR_DIALOG";
export const SHOW_DELETE_DLG = 'SHOW_DELETE_DLG';
export const HIDE_DELETE_DLG = "HIDE_DELETE_DLG";
export const EDIT_MODE_EDIT = "EDIT";
export const EDIT_MODE_INSERT = "INSERT";