export const CLEAR_LESSON = 'CLEAR_LESSON';
export const GET_LESSON_REQUEST = 'GET_LESSON_REQUEST';
export const GET_LESSON_SUCCESS = 'GET_LESSON_SUCCESS';
export const GET_LESSON_FAIL = 'GET_LESSON_FAIL';

export const GET_LESSON_TEXT_REQUEST = 'GET_LESSON_TEXT_REQUEST';
export const GET_LESSON_TEXT_SUCCESS = 'GET_LESSON_TEXT_SUCCESS';
export const GET_LESSON_TEXT_FAIL = 'GET_LESSON_TEXT_FAIL';

export const GET_LESSON_PLAY_INFO_REQUEST = 'GET_LESSON_PLAY_INFO_REQUEST';
export const GET_LESSON_PLAY_INFO_SUCCESS = 'GET_LESSON_PLAY_INFO_SUCCESS';
export const GET_LESSON_PLAY_INFO_FAIL = 'GET_LESSON_PLAY_INFO_FAIL';
export const CLEAR_LESSON_PLAY_INFO = 'CLEAR_LESSON_PLAY_INFO';

export const START_LESSON_PLAYING = 'START_LESSON_PLAYING';
export const SET_LESSON_PLAY_INFO_LOADED = 'SET_LESSON_PLAY_INFO_LOADED';

export const SET_LESSON_NOT_FOUND = 'SET_LESSON_NOT_FOUND';
export const SET_LESSON_TEXT_NOT_FOUND = 'SET_LESSON_TEXT_NOT_FOUND';
